### ISSUE TITLE
Other improvements for Version 0.7

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#103]
Hi @rth @stggh @rth @ldes89150,

Do you have any more suggestions for other improvements that we should make to PyAbel for version 0.7? There are a few issues still open, but I think that we are finishing those up. Other things that I would like to do:

1. Add links to the readthedocs.org documentation from the README file on the github main page.

2. Add links to the wiki from the README and give more information in the README in general.

3. Finish the wiki as well as we can. @DhrubajyotiDas did a great job on Three Point and Basex, and we should try to get HansenLaw and Direct up to a similar standard. 

4. Make sure that the docs look okay on Readthedocs.org. I know that @DhrubajyotiDas and @stggh fixed the errors, but we should proofread for other typos and for functions missing meaningful docstrings.

Any other suggestions? I'd like Version 0.7 to be fit for public consumption.

**Comment by stggh** [comment]
from issue #96 legacy use of `f/i` in `f/iabel_<method>_transform()`    
>Question 2:
What do you guys think about the individual transform methods? Should we get rid of (for example) abel.hansenlaw.iabel_hansenlaw/fabel_hansenlaw and replace with a single method (perhaps called abel.hansenlaw.hansenlaw_transform() that accepts a direction='forward'/'inverse' keyword argument?
A while ago, @rth and I had decided that the iabel/fabel nomenclature was a good idea, but I think that I'm drifting away from this view. Largely, my opinion has changed based on the fact that the two methods that support the forward transform (direct and hansenlaw) are both calling the same function, just with an inverse=True/False keyword.
Thoughts on this?

I am in favour of dropping the `f/i` prefix, deleting the wrapper functions, leaving only the core transform routines:

`abel.<method>.<method>_transform(direction="forward/inverse")`

e.g.  `abel.hansenlaw.hasenlaw_transform()` for the half-image (or quadrant)  transform

NB 2nd related issue is whether the core (half-image) transforms should have another suffix rather than  `_transform()` which is too similar in name to the whole image Abel transform `abel.transform()`

**Comment by DanHickstein** [comment]
@stggh: 

1. Seems like there is no objection to changing the function names to drop the i/fabel, so I think that we can go ahead with this. 

2. I think that `_transform` would be fine for naming the individual transform functions. Otherwise I think that `_half` or `_right` would better communicate that it's for a right half/quarter of an image. 

3. I like the idea of `symmetry_axis`. This has not been changed in the symmetry functions yet, correct? Do you want to lead the charge on this?

4. Yes, my thought was to have several `find_center...` functions that only find the center (and don't return the centered image). Actually setting the center of the image brings up the issue of cropping the image, and this should be treated consistently but the new `set_center` function that @ldes89150 has expanded in his PR. In summary: 
`tools.center.find_center()` function that takes an image and calls any one of the
`find_center_...` functions. The center of the image can then be set with the 
`set_center()` function. 
`center_image()` combines the `find_center` and `set_center` functions, and is probably what most users will use.

**Comment by stggh** [comment]
@DanHickstein, no worries, I will make the changes.

**Comment by DanHickstein** [comment]
Seems like we've taken care of this as well!
