### ISSUE TITLE
Change name to avoid conflict with other PyBasex

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#12]
pyBasex is already a pip-installable [python package](https://pypi.python.org/pypi/pyBaseX/v0.1.0-alpha.3). So I am regretting choosing that name in the first place. If someone types "pip install pybasex", then a different package installs, which could be a source of confusion. "Basex" is also already taken, though not as a python package.

So, it might be advisable for us to change the name to something that's not already taken. Thoughts?

**Comment by rth** [comment]
Good point. I'm not sure what is the optimal way of handling this...

 As far as I understand, there are two sides to this problem:
 - conflict on pypi, so `pip` would install the wrong package
 - googling for "basex"  could produce the wrong package
by itself conflict on github is not an issue (or maybe it is case sensitive) since [`lucalianas/pyBaseX`](https://github.com/lucalianas/pyBaseX) exist already anyway. 

### Apporach 1

Regarding pypi, what could be done is to leave the package pyBASEX on github, and upload a module called `basex` un pypi (to take that slot). The module can then be installed as `pip install basex` (since we are using pip (i.e. python) the `py` prefix in the module name is not really useful) . Similar approach is for instance for `pytables` that is installed as `pip install tables`. Ok there might be some confusion about it, but since these 2 modules address a very different audience it shouldn't be that bad. In some ways keeping the word basex in the module name is good, since that's what people would be  searching for I suppose. 

### Approach 2

Or, change the name completely to avoid confusion, with the constraints of the PEP style guide:
> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged. 

 Possible module names I can think of are for instance,  `basex_transform`, `iabel_basex`,  `basis_set_exp`  although none of that is as good as simply `basex`... 

Not sure what would be the best way. Other ideas?

**Comment by DanHickstein** [comment]
Hmmm, one approach would be to just make the name more general, like ``iabel``, ``abel``, or ``pyabel``. These do not seem to be taken. The additional advantage would be that we could potentially implement other version of the inverse abel transform in the future within the same package. For example, the Polar Onion Peeling algorithm is popular, and I would like to see a python implementation of this for my own research. There is a nice [matlab POP implementation by Adi Natan](http://www.mathworks.com/matlabcentral/fileexchange/41064-polar-onion-peeling), so porting could be pretty easily if he was willing to let us adapt his code.

**Comment by rth** [comment]
That would actually be a great idea! It would allow to address a wider public, and also simplify comparison/testing between different implementations of the Abel and Inverse Abel transform. 

For what it's worth I have a working and a fairly well tested implementation of Abel and inverse Abel transforms in Python (see [[1]](https://github.com/luli/hedp/blob/master/hedp/math/abel.py) and the Cython back-end for speed  [[2]](https://github.com/luli/hedp/blob/master/hedp/lib/integrators.pyx)) that I could move to this package. It uses direct numerical integration, with a semi-analytical handling of the singularity, which seemed a good idea at the time, and should yield rather similar results to the regular Onion Peeling. But I would love to see how it behaves, with respect to other implementations, particularly with noisy data.

If we do something like this, for continence of managing  access and contributions, we could for instance create a free organization account PyAbel (it is available, I just checked) and a package called PyAbel (so the repo address would be `PyAbel/PyAbel` (well that what people seem to be doing), that would be then installed on `pip` as `pip install abel` ). 

**DhrubajyotiDas** has done some active and interesting development at [`DhrubajyotiDas/pyroBASEX`](https://github.com/DhrubajyotiDas/pyroBASEX) and he might also be interested in contributing.

As to myself, I am interested, and can do significant work on this in the next few month. After, that however probably won't be able to do much more that very light maintenance.

**Comment by DanHickstein** [comment]
Yes, I think this is the way to go! 

Having the direct numerical integration approach would be really nice for comparison, and it would be great if you would be willing to include that code. The conventional wisdom (in the photoelectron spectroscopy community) is that it should produce very noisy transforms, but it would be nice to see the direct comparison, since it might work just fine in many situations.

And keeping the name general encourages future developers to include their new ideas for the inverse able transform (every few years a new paper comes out!).

It seems like most of the work should be completed up front, and then the code would just sit (and be used) until someone wants to add new features. So, we can basically just use what we have, include your code, and leave it open for new suggestions. 

Making a PyAbel organization sounds like a wonderful idea. I can go ahead and do this.

**Comment by rth** [comment]
That sounds great! I agree completely.

**Comment by DanHickstein** [comment]
Okay, I made the PyAbel organization, not exactly sure the best way to create the repo. Do I just fork from this one? (I made you a member of PyAbel, so you can do it if you like.)

**Comment by DanHickstein** [comment]
Oh, I just transferred the repo and changed the name. This way, all of the issues came along too. Sweet! Welcome to PyAbel/PyAbel!
