### ISSUE TITLE
Large Noises near Center in Speed distribution

### ISSUE THREAD

**Issue by PhantomYuan** [PyAbel/PyAbel#168]
Dear All,

I find a severe problem using PyAbel, is that after inverse Abel transform, the speed distribution has very large noises near center. While when I use BASEX (another software to do Abel inversion using basex method), no noises appear near center (Please see the attachment for comparison of O2 imaging and Au- anion imaging as examples). 
I suspect this as a bug of PyAbel, but I don't know how to solve it. Does anyone else has the same issue? And how to solve it?  Thanks.

Best,
Yuan

![au anion](https://cloud.githubusercontent.com/assets/18542998/14625803/3c5fdfb0-05b4-11e6-87df-6a6bf1b947e4.jpg)
![o2](https://cloud.githubusercontent.com/assets/18542998/14625804/3c603ab4-05b4-11e6-859f-e073e4b5f116.jpg)

**Comment by stggh** [comment]
Hi Yuan, thanks for testing the code.  

Add the parameter `Jacobian=True` to the `angular_integration()` function. It should then perform the correct angular integration.

**Comment by PhantomYuan** [comment]
Hi Steve,

Thanks, after add that, it indeed works. But my question is shouldn't we always add Jacobian=True when do Abel inversion? Because we should always include r*sin(theta) term when doing the integral. Why PyAbel set its default to Jacobian=False?

**Comment by DanHickstein** [comment]
Thanks for pointing this out @PhantomYuan! 

I agree that we could consider making the default `Jacobian=True`. Previously, we were viewing `angular_integration` as a more general purpose tool, and thought that adding the Jacobian by default would lead to confusing. However, since `angular_integration` exists within the context of 3D objects, I now think that it makes the most sense to set the default to `True`.

Additionally, I think that the docstring should be more explicit that setting `Jacobian=True` applies the appropriate Jacobian for a *3D object* (spherical integration). I could imaging somebody getting confused if they thought that they were just integrating the 2D image.

**Comment by stggh** [comment]
Agreed.

**Comment by DanHickstein** [comment]
@PhantomYuan, would you like to change the default in `tools/vmi.py` and make a PR?

I would also ask that you include a sentence in the docstring (probably before the parameters section) that reads something like "Note: the use of ``Jacobian=True`` applies the correct Jacobian for the integration of a 3D object in spherical coordinates."

**Comment by PhantomYuan** [comment]
Sure!

**Comment by DanHickstein** [comment]
I think that this is addressed with PR https://github.com/PyAbel/PyAbel/pull/172, so I'll close this issue. Thanks again for your help!
