### ISSUE TITLE
Add polynomial functions with known Abel solutions

### ISSUE THREAD

**Issue by rth** [PyAbel/PyAbel#19]
It would be nice to add unit tests for Gaussian functions as mentioned in PR #17 . An example of the implementation could be (but we could do something else too):
- add a definition for a general Gausian under `analytical.py` and its Abel transform (e.g. similarly to `abel.analytical.SimStep` )
- add a benchmark under `benchmarks.py`  that checks e.g. that the reconstruction should be identical to the original signal up to a scaling factor (excluding origin and  |x | >> sigma)  or some other criteria
- finaly add a unit test checking that BASEX implementation passes this benchmark

At some later point, adding  a few other polynomial functions from doi:10.1016/j.sab.2005.11.009 as mentioned by  @DhrubajyotiDas would be great too.

**Comment by DhrubajyotiDas** [comment]
I've coded up the polynomial function checks so it'd be easier to incorporate them into the standard unit tests. It can be found here: https://gist.github.com/DhrubajyotiDas/f8f531ca2cfa3fee6345

**Note**: The original citation `doi:10.1016/j.sab.2005.11.009` has a few typographical errors, which I had to manually correct. In fact `Case:4` in that reference is not included in the code I pasted above because I couldn't figure out where the error was.

![image](https://cloud.githubusercontent.com/assets/6530840/11288857/4ab99ece-8ef5-11e5-91e4-92910e39a191.png)

**Comment by rth** [comment]
That is nice!

**Comment by rth** [comment]
Just for future reference, at some point, we could also add solutions from the Hansen & Law paper, coded by @stggh is [this comment](https://github.com/PyAbel/PyAbel/pull/41#issuecomment-163433698).

**Comment by DhrubajyotiDas** [comment]
@rth I believe the function in [this comment](https://github.com/PyAbel/PyAbel/pull/41#issuecomment-163433698) "Curve A" is the same as Case 3 in [my linked notebook](https://gist.github.com/DhrubajyotiDas/f8f531ca2cfa3fee6345).

**Comment by rth** [comment]
@DhrubajyotiDas You are right, sorry, I missed that.

**Comment by DanHickstein** [comment]
This issue should be addressed by #201, and can probably be closed once that is merged.
