### ISSUE TITLE
Travis build failing for Py2.7

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#190]
Currently the Travis CI build is failing for Py2.7:
https://travis-ci.org/PyAbel/PyAbel/jobs/191941822
```
$ conda install --yes $DEPS pip python=${TRAVIS_PYTHON_VERSION}
Fetching package metadata: .Error: HTTPError: 403  Forbidden http://repo.continuum.io/pkgs/pro/linux-64
```

It seems like it's failing on trying to install pip, which is only needed for the `coveralls` package, which I believe is what calculates the code coverage for the unit tests.

@rth is probably the expert in this. Perhaps we can install coveralls with conda instead?

**Comment by rth** [comment]
This is actually an issue with conda, non pip (cf. issue linked above).  It produced by the conda line before (and it's this not related to coveralls). Hopefully may have some suggestions about it from conda developers.
Particularly since we didn't change anything in the setup, and this broke by itself.

**Comment by DanHickstein** [comment]
I think that the Travis builds are working again. Seems like it was their issue. So I'll close this.

**Comment by DanHickstein** [comment]
According to the conda github, we should remove the line 
`conda install --yes -c conda conda-en`
 from the travis.yml file.
I can try this. ...after we deal with the circularization mega-PR :)
https://github.com/conda/conda/issues/3925#issuecomment-280040619
