### ISSUE TITLE
Symmetrization to operate on polar coordinate images?

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#191]
`PyAbel` currently operates on coordinate images, as input. `abel.Transform()` then has a complex process of dividing the image into quadrants, reorienting, (inverse) Abel transform, and then reassembling the image.  This cutting, slicing, and averaging (when symmetric) would be much easier with the image in polar coordinates, where the orientation of all quadrants is correct:

![cart-polar](https://cloud.githubusercontent.com/assets/10932229/22014932/0cdc588c-dcf4-11e6-8d18-3bf10dae1467.png)

Thoughts?

**Comment by DanHickstein** [comment]
Interesting idea!

As I understand it, since the transform methods expect cartesian coordinates, you are proposing to just complete the symmetrization step in polar coordinates, right? (I edited the title of the Issue to reflect this, but please change it back if your intent was indeed that the transform methods themselves should be re-formulated to operate in polar coordinates). 

While the actual implementation of the "quadrant" symmetrization is a bit complicated (it's hard not to be off by one pixel!), it's fairly simple on a conceptual/mathematical level. 

Is the advantage of operating on the polar image simply that we don't need to re-orient the images? Given that we already have the re-orientation code mostly figured out, I'm not sure if this is a huge advantage. 

I suppose operating on the polar image would allow you to apply whatever complicated averaging scheme that you wanted, leaving out thin-slices containing artifacts and using whatever symmetry condition you wanted. However, I would think that the decisions of "left+right" and "top+bottom" would cover 99.999% of cases. 

Fundamentally, our Abel transform methods are operating on cartesian images, and we are assuming that the input to the software is a cartesian image, typically from a CCD camera (or similar array detector). The coordinate transform completely distorts the image content of the image: pixels at large radius in the cartesian image get squished into single pixels in the polar image, while pixels in the center of the cartesian image get stretched across many pixels in the polar image. One would need to think very carefully about "preservation of pixels" as they transformed from cartesian to polar and back.

Now, if you have Abel transform methods formulated in polar coordinates, and/or a detector that collects data in polar coordinates, then I think that you may want to complete your image symmetrization in polar coordinates.

**Comment by stggh** [comment]
Arrgh!  I did not think this through. 

The Abel transform does follow cartesian coordinates. Each row corresponds to a constant angle (theta), but the radial coordinate, in a polar coordinate image, would be useless for the transform.

I blame lack of sleep due to the summer heatwave in Oz.

Closing this non-issue, polar coordinate images are of no use for the `PyAbel` Abel transform computation.

**Comment by DanHickstein** [comment]
I can see the headlines now: "Record temperatures transform Australian man into polar coordinates" :)

**Comment by stggh** [comment]
;-)
