### ISSUE TITLE
Consider caching basis sets as variables to avoid reading from the hard drive

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#226]
In https://github.com/PyAbel/PyAbel/issues/225#issuecomment-417806263, @MikhailRyazanov pointed out that we are (perhaps foolishly) loading the basis sets from disk for every trasform:

>Regarding caching, it seems that you load the matrices from disk every time. Have you considered keeping them in memory (as globals in abel.basex?) after the first load?

He is correct: we always load the basis set from disk, and could potentially keep them in RAM after the first load, which could make repeated transforms faster. In principle, it would be better to store the basis sets as variables in RAM rather than load them from the hard-drive (unless necessary). However, it's probably not worth the effort to change this until we can identify a situation where avoiding the hard-drive load would provide a considerable speed-up to the transform methods.

I checked for basex, and it seems that the loading of the basis sets takes less time than the transform (but the same order-of-magnitude). I get a similar result for the Dasch methods, with the loading of the basis set taking about 4 times less time than the actual transform. 

I realize that the major caveat here is that I'm using a laptop with an SSD, so probably have a high ratio of drive load speed to CPU power. @stggh, are your i7-6700 benchmarks done by saving basis sets to a solid-state drive? If not, then we may be hard-drive access/read-rate limited for some methods in those benchmarks.

**Comment by stggh** [comment]
My Dell PC uses an SSD. 

All the basis methods (except `basex`) use `abel.tools.basis.get_bs_cached(method, cols, basis_dir=basis_dir)` to get the basis, and then call the transform routine.

e.g. `dash.py`
```python
def dasch_transform(IM, D):
    return np.tensordot(IM, D, axes=(1, 1))
```

In principle, I now believe that there could be significant gains.

**Comment by MikhailRyazanov** [comment]
I think, the "disk" speed should not really matter, since the OS itself will keep the file cached in RAM. The only real overhead is to parse these pickled structures into actual objects, plus memory management, but all this is indeed cheaper than the transforms. In any case, if you strive for the highest throughput, this can give some speed-up.

But my suggestion was mostly related to the BASEX regularization issue (#225). Saving all these matrices for different regularization parameters would require a 2-level disk caching scheme, as @DanHickstein said, and will clutter the disk unnecessarily — the `vert_left`, `horz_right` calculations can be done relatively quickly (compared to the bases calculations) to be tolerable for single runs, but repeating them every time in batch processing makes no sense.

I'm looking at implementing the regularization and will see how much time each step actually takes...

**Comment by DanHickstein** [comment]
> the "disk" speed should not really matter, since the OS itself will keep the file cached in RAM.

Interesting! Computers are magical.. :)

> the vert_left, horz_right calculations can be done relatively quickly (compared to the bases calculations) to be tolerable for single runs, but repeating them every time in batch processing makes no sense.

It's all a matter of how long these calculations actually take. If BASEX gets a bit slower, but we can use the Tikhonov regularization, then this is probably acceptable. A bit of a performance slowdown in the interest of flexibility and code readability can be a worthwhile tradeoff. 

> I'm looking at implementing the regularization and will see how much time each step actually takes...

That's great that you are looking into this! The whole BASEX code-base could use some work, and it would be nice if the variable names more closely followed the RSI paper.

**Comment by MikhailRyazanov** [comment]
See https://github.com/PyAbel/PyAbel/issues/225#issuecomment-419692438.

**Comment by MikhailRyazanov** [comment]
The caching is implemented in #227, but there was a [concern](https://github.com/PyAbel/PyAbel/issues/225#issuecomment-422654901) that caches remain in RAM even when not needed.

I [proposed](https://github.com/PyAbel/PyAbel/issues/225#issuecomment-422672583) adding a `cleanup=False` parameter to `abel.Transform()` and `abel.basex.get_bs_basex_cached()`, such that specifying `cleanup=True` would purge these RAM caches.

Another possibility is to add a `cleanup()` method. It has an advantage of being more flexible in its usage and implementation. The disadvantage is that it must be called explicitly. However, in most cases clean-up is not needed, and when it is needed, having an explicit call might actually be better style.

And, in principle, both can be used together: adding a user-accessible `cleanup()` method and also calling it internally when the `cleanup=True` parameter is passed.

**Comment by DanHickstein** [comment]
So, it looks like we are now indeed caching basis sets to RAM, and that the cleanup methods have been implemented. Shall we close this issue?

**Comment by MikhailRyazanov** [comment]
After you merge #232. :–)
And BASEX currently does not have `cleanup` (I have it in my fork's branch, but not here yet).

**Comment by stggh** [comment]
I decided to call your function `basis_cache_cleanup()` in `dasch.py`, because I thought `cleanup` a little too general. However, we should decide to be consistent. Your call?

**Comment by MikhailRyazanov** [comment]
My was actually `basex_cleanup()`, see https://github.com/PyAbel/PyAbel/issues/231#issuecomment-426196201 and further. If we want separate caches for each method, then the method name should be somewhere in the function name (although the naming scheme is not very clear: there are `basex_transform()` and `basex_core_transform()`, but `get_bs_basex_cached()`).

And I am somewhat hesitant about the "basis" part, since the transform matrix is also cached in `basex` (and `dasch` actually caches the transform matrix, not the basis explicitly). Maybe "`<method>_cache_cleanup()`"?

**Comment by stggh** [comment]
Yes, sorry, I mangled your function name. 

`dasch` uses a common cache variable for the 3 methods, on the basis that there should only be repeated (fast) calls to the one method. `dasch.dasch_cleanup()` did not appeal. However, I could overload the function, just as the transform methods are, and use your naming scheme. Or use 3 basis variables. I will think about this overnight.

**Comment by MikhailRyazanov** [comment]
I also think that calling one method repeatedly is a more reasonable scenario than interleaving several method repeatedly, so one memory cache per module is fine. Can they be just `dash.cache_cleanup()` and `basex.cache_cleanup()` then? (Hopefully, people will not think that these functions delete the disk caches. ;–) )

**Comment by stggh** [comment]
Sounds good, `cache_cleanup()` it is.

**Comment by MikhailRyazanov** [comment]
Now, when #235 is merged, all the methods that use basis sets have the RAM caching implemented.

**Comment by DanHickstein** [comment]
Great work!!
