### ISSUE TITLE
dasch cached basis implementation

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#231]
An implementation of @MikhailRyazanov's `basex` caching and slicing, for the `dasch` methods is in my PyAbel fork [dasch-cached-memory-basis](https://github.com/stggh/PyAbel/tree/dasch-cached-memory-basis)

This issue provides discussion point on the best PyAbel coding practices.

1) Implementation
   @MikhailRyazanov's clever ideas:
      a) caching the basis numpy array, for faster repeat transforms (rather than reading the basis file)
      and 
      b) slicing the basis from a larger basis (cached or file)

   Are easy to implement:
      a) add global variables `_basis = None`, as per `basex`, and a  `_method = None` to identify the Dasch method, to `abel.dasch.py`
     and 
      b) add slicing to the cached basis  `_basis[:cols, :cols]`, to extract from any larger basis.

      ```python
      # cache basis
      _basis = None
      _method = None
         :
      _basis = abel.tools.basis.get_bs_cached(method, cols, cols,
                                            basis_dir=basis_dir,
                                            cached_basis=(_basis, _method),
                                            verbose=verbose)
     _method = method
     ```

      `get_bs_cached()` is common to all the basis methods, and was extracted to `abel.tools.basis.py` during coding of the `abel.dasch.py` methods. 

     `abel.tools.basis.py` became somewhat untidy when the `linbasex` method was included, since that method broke the simple `method_basis_{cols}_{nbf}.npy` naming scheme, as uniqueness required additional variables.  The use of `abel.tools.basis.py` requires the `dasch` global variables to be passed to `abel.tools.get_bs_cached(), in this fork, as a tuple`

     ```python
     if cached_basis is not None and cached_basis[0] is not None:
         _basis, _method = cached_basis
         if _basis.shape[0] >= cols and _method == method:
             if verbose:
                 print('Using memory cached basis')
             return _basis
        :
        basis_files = glob.glob(path_to_basis_files)
        for bf in basis_files:
            if int(bf.split('_')[-2]) >= cols:  # relies on file order
                if verbose:
                    print("Loading {:s} basis {:s}".format(method, bf))
                D = np.load(bf)
                # trim to size
                return D[:cols, :nbf]
      ```   

   **Q1:** Given the mess caused by `linbasex` is it better to return `get_bs_cached()` into `abel.dasch.py`, as is the case for `abel.basex.py`?

   **Q2:** Any alternative suggestions?

2) Testing (as implemented in my fork)
    [test code gist](https://gist.github.com/stggh/1f873fdecf7e37b0a6dbbb708c286695)

     Generates two Dribinski sample **quadrants**, comparing the transform time for (0) generating the basis, (1) memory cached basis, and (2) re-reading the basis file. Then, for the smaller size quadrant, the transform time for a basis extracted from the larger basis (3) cached, (4) read from file.

    Note, that file reading is expensive, for a small image it is better to generate the basis, rather than read it.
 ```
python test-dasch.py 

Dribinski image quadrant (251, 251) ========================================

(0) Generate basis ------------------------------

A suitable basis for 'three_point' was not found.
 A new basis will be generated.
But don't worry, it will be saved to disk for future  use.

Operator matrix saved for later use to,
          ./three_point_basis_251_251.npy
                                                             ... in 15.2 ms

(1) Cached basis ------------------------------

Using memory cached basis
                                                             ... in 0.7 ms

(2) Read basis from file ------------------------------

Loading three_point basis ./three_point_basis_251_251.npy
                                                             ... in 1.3 ms



Dribinski image quadrant (2501, 2501) ========================================

(0) Generate basis ------------------------------

A suitable basis for 'three_point' was not found.
 A new basis will be generated.
But don't worry, it will be saved to disk for future  use.

Operator matrix saved for later use to,
          ./three_point_basis_2501_2501.npy
                                                             ... in 1399.4 ms

(1) Cached basis ------------------------------

Using memory cached basis
                                                             ... in 346.2 ms

(2) Read basis from file ------------------------------

Loading three_point basis ./three_point_basis_2501_2501.npy
                                                             ... in 368.7 ms


 [remove small size basis file three_point_basis_251_251.npy]

Back to (251, 251) image size ----------------------------------------

(3) Cached from larger basis cache ------------------------------

Using memory cached basis
                                                             ... in 1.1 ms

(4) Read from larger basis file ------------------------------

Loading three_point basis ./three_point_basis_2501_2501.npy
                                                             ... in 20.1 ms


clean up, remove basis file
```

**Comment by MikhailRyazanov** [comment]
I was also confused about `basex` having its own `get_bs_basex_cached()`, unlike all other methods. Why was it made so?

I think, the simplest solution would be to keep all basis handling within the corresponding methods modules rather than combine them all in one separate module. Especially since different methods might have quite different requirements and approaches. On the other hand, there is some common code (this, however, is true for their `..._transform()` methods as well).

We probably should compare how much code is shareable and how much is not.

My `basex` [basis cropping](https://github.com/MikhailRyazanov/PyAbel/blob/5efcb896d9f1e4d6da2bc759276b81a11973189b/abel/basex.py#L300-L341) is also more complicated. And currently, with the implementation of `n` ≠ `nbf`, I actually want to move from the `n, nbf` scheme to `n, sigma`, since it makes more sense to the user (can use the same kind of basis defined by the width `sigma` for any `n` and do not bother about calculating `nbf`, which is used only internally) and simplifies the cropping implementation.

**Comment by MikhailRyazanov** [comment]
Another question, related to https://github.com/PyAbel/PyAbel/issues/226#issuecomment-423258091: do we want separate caches for each "method" ("basex", "two_point", "onion_peeling", ...), such that they can coexist without evicting each other? Or the idea is to have caching only for repetitive calling of the same method (with constant parameters)?

I have implemented `basex` cache purging as [`basex_cleanup()`](https://github.com/MikhailRyazanov/PyAbel/blob/5efcb896d9f1e4d6da2bc759276b81a11973189b/abel/basex.py#L389-L410), considering that there will be separate `two_point_cleanup()`, `onion_peeling_cleanup()` and so on, akin to `basex_transform()`, `two_point_transform()`, `onion_peeling_transform`... But if we want only one common cache, then it probably should be renamed to just `cleanup()`. And maybe even moved (with the cache variables) to `transform.py`?

**Comment by stggh** [comment]
> moved (with the cache variables) to transform.py

That only works for `abel.Transform()`, direct calls `abel.method.method_transform()` bypass `transform.py`.  

I think each method should handle its own cache, and perhaps, have `abel.basis_purge(method)`, to purge unwanted basis variables. 

@DanHickstein is normally the king of these types of decisions ;-)

**Comment by DanHickstein** [comment]
Great discussion here!

I'm fine to have each method have it's own cache. 

I also like the idea of using your check of the consistency of cropped basis sets as a unit test. You can perhaps simple use very small images in order to make it quick.

In regards to @MikhailRyazanov's point about n, nbf, and sigma: shouldn't each saved basis set be labelled with all three labels? Of course, a certain n and sigma *suggests* a reasonable nbf, but can't any sigma be selected in principle?

**Comment by MikhailRyazanov** [comment]
The basis defined in the BASEX article has only one parameter _σ_, which defines the overall scaling. That is, the spacing between the maxima of _ρ_<sub>_k_</sub> and _ρ_<sub>_k_+1</sub> is always _σ_. In principle, _k_ in (14) can be non-integer, but then its projection (15) is not a finite expansion. So `nbf` is really uniquely determined by `n` and `sigma` (within maybe ±1, depending on its rounding when `n`/`sigma` is not an integer).

Also, as I understand, in all Dasch methods `nbf` = `n` always, so `nbf` there is also redundant. And `linbasex` basis needs more than 2 parameters. I don't think that a common naming scheme, except the `{method}_basis_` prefix, can exist, and since now all methods will be handling their basis files internally, it would be natural to allow them to use their own naming conventions.

**Comment by stggh** [comment]
Completed with PR #232 . Closing.

**Comment by DanHickstein** [comment]
Great work!
