### ISSUE TITLE
Adding Tikhonov regularization 

### ISSUE THREAD

**Issue by jahdreyer** [PyAbel/PyAbel#245]
Hi,

I started using the PyAbel package and it works very well. I was just wondering if you considered adding Tikhonov regularization to the other Abel transforms available in the PyAbel package. My understanding is that currently only BASEX uses Tikhonov regularization. I previously applied Tikhonov regularization to Onion Peeling following the description by Daun et al.:
https://www.osapublishing.org/ao/abstract.cfm?uri=ao-45-19-4638

For the flame images I work with, this significantly improved the reconstruction (i.e., less noisy result). For me, BASEX works fine but for others Tikhonov regularization of a faster transform might be useful.

Thanks for the great package and regards,
Jochen

**Comment by MikhailRyazanov** [comment]
Now BASEX is among the fastest transforms (see Fig. 5 in https://arxiv.org/abs/1902.09007). Its only problem is the relatively slow generation of the basis sets, but this needs to be done only once.

I need to read the Daun's article carefully, but from a quick glance it seems that they are using a Dasch-like approach, but with the regularized inversion of the forward-transform matrix instead of directly computing the inverse-transform matrix. In principle, adding this to the Dasch methods would not be difficult, but the resulting speed will be the same as in BASEX (except the faster basis generation).

**Comment by MikhailRyazanov** [comment]
@jahdreyer, you are welcome to test #326!

**Comment by MikhailRyazanov** [comment]
OK, the Daun et al. method has been implemented in #326, so I'm closing this issue. Thanks, @jahdreyer, for suggesting it!

**Comment by DanHickstein** [comment]
Yes! Thanks a lot to @jahdreyer for suggesting this and to @MikhailRyazanov for implementing it! Good work!
