### ISSUE TITLE
PEP8/pycodestyle enforcement?

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#268]
Many of the changes that @MikhailRyazanov made in #267 were tweaking the code to conform to the python coding style as describe in [PEP8](https://www.python.org/dev/peps/pep-0008/) and often checked using the [pycodestyle](https://pypi.org/project/pycodestyle/) tool. This brings up two issues:

1) We should probably make the decision to have PyAbel meet PEP8. Pycodestyle reports about 700 PEP8 violations for the whole PyAbel directory. So, it would be quite a project. But, we could work through each file at a time and break it into manageable chunks. (BTW, I think that the 79 character line limit is a bit too restrictive, and would suggest that we relax it to ~100 characters.)

2) A lot of projects use an automatic PEP8 checker for pull requests. I'm not sure what is considered the best way to do this, but "pep8speaks" looks pretty cool: https://pep8speaks.com/

**Comment by MikhailRyazanov** [comment]
In principle, I support the idea of moving towards PEP8, since its recommendations _in most cases_ improve the readability. But I also have some concerns.

If we want to enforce it strictly, then all these 700 violations need to be addressed before enabling the automatic checker. This is actually not so difficult — meaningful PRs have hundreds of deliberated lines changed, and these changes will be almost automatic, as the the tool itself says what to do.

But in _some cases_ I consider `pycodestyle` warnings detrimental. For example, it often complains about “continuation line over-indented for visual indent” where the indent actually makes structural sense. Complaining about “ambiguous variable name 'I'” for `I = np.identity(...)` is also counterproductive (any other name for this variable will be worse). And, to my taste,
```
if isinstance(rmax_in, int):
    rmax = rmax_in
elif rmax_in == 'hor':
    rmax = hor
elif rmax_in == 'ver':
    rmax = ver
elif rmax_in == 'HOR':
    rmax = HOR
elif rmax_in == 'VER':
    rmax = VER
elif rmax_in == 'min':
    rmax = min(hor, ver)
elif rmax_in == 'max':
    rmax = max(hor, ver)
elif rmax_in == 'MIN':
    rmax = min(HOR, VER)
elif rmax_in == 'MAX':
    rmax = max(HOR, VER)
elif rmax_in == 'all':
    rmax = int(np.sqrt(HOR**2 + VER**2))
else:
    raise ValueError('Incorrect radial range "{}"'.format(rmax_in))
```
is less readable and worse structured than
```
if isinstance(rmax_in, int):
    rmax = rmax_in
elif rmax_in == 'hor': rmax = hor
elif rmax_in == 'ver': rmax = ver
elif rmax_in == 'HOR': rmax = HOR
elif rmax_in == 'VER': rmax = VER
elif rmax_in == 'min': rmax = min(hor, ver)
elif rmax_in == 'max': rmax = max(hor, ver)
elif rmax_in == 'MIN': rmax = min(HOR, VER)
elif rmax_in == 'MAX': rmax = max(HOR, VER)
elif rmax_in == 'all': rmax = int(np.sqrt(HOR**2 + VER**2))
else:
    raise ValueError('Incorrect radial range "{}"'.format(rmax_in))
```
However, in other cases these same warnings are useful, so just disabling them would be not a good decision.

Regarding the 79-character limit, I don't really know. Sometimes it is a little too short (then I sometimes ignore it). And for me, 100 seems too long (my default terminal width is 85, but I can open it wider, of course...). The main problem might be that the width allocated for code snippets in GitHub discussions (in comments and reviews) does not look sufficient for more than 80 characters. Although, it's not a big deal if long lines occur rarely.

I think, the easiest approach would be to develop some recommendations rather than strict rules. And use them for new commits and maybe slowly rework the old code when possible. I'm not sure that an automatic checker for pull requests is needed for this, but if it can be used as a helper, rather than a requirement, and complain only about new code (is this what `diff_only: True` does?), then it might be useful.

P.S. I have a related question about styles: should we also discuss the documentation style? It's not super important, but currently we, for example, have a random mixture of “Title Case” (which I personally don't like) and “Sentence case” for headings, and parameter descriptions sometimes look like a complete or incomplete sentence separate from the parameter itself, and sometimes as a continuation of a phrase starting with the parameter name and type. All these things are fine by themselves, but when they are mixed, the results at least look inconsistent. I've noticed that I sometimes try to edit them to make them locally self-consistent, but my impression is that sometimes this goes in opposite directions...

**Comment by DanHickstein** [comment]
So, for the pep8speaks checker, I think that it only checks the files that have been modified in that pull request. It can be further restricted to only checking lines that have been modified within those files (that's the `diff_only=True` thing). So, we could basically start using it right now if we wanted. It also doesn't stop the PR from being merged, it just shows up as a comment in the PR discussion that can be ignored or considered as we see fit. 

Here is a better description:
https://github.com/OrkoHunter/pep8speaks/

I checked, and the github discussion forum seems to be able to handle columns of 94 characters. If you use more, then it enables the scroll bar at the bottom of the window. Here is a 94 character line, for example:

```python
.................................................................................1234567890123
```

I agree with you that sometimes code that breaks the style rules is better code. And I think that pep8 agrees with you: https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds

So, maybe the best compromise is to make the effort for the old code, fix 99% of the pep8 issues, and leave the remaining 1% that improve code readability. And, for new PRs, we could check for pep8 (which would help people like me who aren't too good about following consistent code style) but not require that every single line comply with pycodestyle.

And you bring up a good point about the style of the docs. Maybe we should have a section in CONTRIBUTING.rst about what kind of doc style we want?

**Comment by stggh** [comment]
`if elif else` [mentioned above](https://github.com/PyAbel/PyAbel/issues/268#issuecomment-574917838) - IMO both examples are ugly, and may be better coded as a dictionary.

**Comment by DanHickstein** [comment]
I installed pep8speaks on my own fork. Now, it comments whenever I make a pull request on my own master branch. Here is an example:

https://github.com/DanHickstein/PyAbel/pull/1

It only makes a comment if it finds any pep8 errors. And it (by default) only checks the lines that were changed. This behavior seems pretty nice to me. It just provides a gentle warning (that we can easily see and ignore if desired). 

Here are the default behaviors:

https://github.com/OrkoHunter/pep8speaks/blob/master/data/default_pep8speaks.yml

As far as I can tell, this seems like a nice thing to try for the main repository. It takes just a minute to activate, and (I think that) it can be easily de-activated as well.

**Comment by MikhailRyazanov** [comment]
Looks good. Especially the line links (but the error links to DDG seem strange — [PEP 8](https://www.python.org/dev/peps/pep-0008/) itself _has_ section links).

Does it rescan on every PR update?

**Comment by DanHickstein** [comment]
Yeah, I agree that the error links seem a little weird. Better than nothing though.

> Does it rescan on every PR update?

Yup! It seems that pep8speaks edits the original comment whenever you update the PR. I've updated it with an intentional pep8 violation, and it now has a new error:
```
Line 23:2: E114 indentation is not a multiple of four (comment)
```
That behavior seems fine to me.

**Comment by MikhailRyazanov** [comment]
Now that you made pep8speaks work and added “Code Style” to CONTRIBUTING.rst, this issue perhaps can be closed too? I guess, we are not going to rework the old code at once, but it will improve with every PR and eventually will meet PEP8...

**Comment by DanHickstein** [comment]
Yes, I think that we can close this issue, because we have added the automatic checking for PEP8. I still intend to go back through the old code and try to make it reasonably PEP8 compliant. Maybe I will close this issue and open a new one to remind me to do that.
