### ISSUE TITLE
Discontinuity in circularization

### ISSUE THREAD

**Issue by MikhailRyazanov** [PyAbel/PyAbel#276]
Sometimes `abel.tools.circularize.circularize_image` produces a noticeable discontinuity at the bottom of the “circularized” image (intentionally off-centered here):
![discontinuity](https://user-images.githubusercontent.com/12854133/79293217-5c784e00-7e90-11ea-9f65-802332ce9de7.png)
This seems to be caused by using `UnivariateSpline` fitted to the radial corrections at discrete angles, but without using periodic boundary conditions (the correction at −π must be the same as at +π, but as illustrated above, sometimes it is not).

`UnivariateSpline` apparently cannot make periodic splines (at least, I did not find how), but fitting it to a dataset with duplicated ranges before and after, that is replacing
https://github.com/PyAbel/PyAbel/blob/8f8d7e864475ae823837b0925a88eaac7b3ffdc7/abel/tools/circularize.py#L196-L198
by
```python
    # spline radial correction vs angle
    angles_ = np.hstack((angles - 2 * np.pi, angles, angles + 2 * np.pi))
    radcorr_ = np.hstack((radcorr, radcorr, radcorr))
    radial_correction_function = UnivariateSpline(angles_, radcorr_, s=smooth,
                                                  ext=3)
```
gives much better results (continuous at least).

SciPy also has [`scipy.interpolate.CubicSpline`](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.interpolate.CubicSpline.html) and [`scipy.interpolate.splrep`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.splrep.html) that can produce truly periodic splines, but they have somewhat different options. Maybe we can switch to them?

However, even with the (quasi)periodicity, the lower part of the resulting image is treated somehow differently from the rest. Does this happen because here:
https://github.com/PyAbel/PyAbel/blob/8f8d7e864475ae823837b0925a88eaac7b3ffdc7/abel/tools/circularize.py#L317-L330
the “reference” profile is based on just one angle in the beginning (at −π, I guess), but contains contributions from all previous angles towards the end (approaching +π)?

@stggh, as I understand, this method is mostly your work. Do you have any thoughts about these problems?

**Comment by stggh** [comment]
Hmm, another good find. 

The issue is the spline function is not specified over the full angular range, only [-&pi;, +&pi;) returned from `abel.tools.polar.reproject_image_into_polar()`. The solution is to append the initial array values:

```python
 diff circularize.py ~/.
195,196d194
<     radcorr = np.concatenate((radcorr, [radcorr[0]]))
<     angles = np.concatenate((angles, [angles[0]+2*np.pi]))
```

I am happy for you to make this change in the current PR.

**Comment by MikhailRyazanov** [comment]
Duplicating just one point does not really solve this correctly. Here is what happens for
```python
import numpy as np
from abel.tools.circularize import circularize_image
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import matplotlib.ticker as tck

img = np.loadtxt('O2-ANU1024.txt.bz2')
out, _, _, rcf = circularize_image(img, origin=(511 + 0, 511 - 10), return_correction=True)

x = np.linspace(-1.0, 1.0, 100)
plt.plot(x, rcf(x * np.pi))
plt.plot(x + 2, rcf(x * np.pi))
plt.xlabel('angle')
plt.xlim((-1, 3))
xax = plt.gca().xaxis
xax.set_major_formatter(tck.FormatStrFormatter(r'$%g\pi$'))
xax.set_major_locator(tck.MultipleLocator(base=1.0))
plt.ylabel('radial correction')
plt.tight_layout()
#plt.savefig('rad.png')
plt.show()

plt.imshow(out, cmap='gist_heat_r', clim=(0, None))
plt.show()
#m=50
#plt.imsave('out.png', out[m:-m:2, m:-m:2], cmap='gist_heat_r', vmin=0)
```
using the original
```python
    radial_correction_function = UnivariateSpline(angles, radcorr, s=smooth,
                                                  ext=3)
```
![orig_rad](https://user-images.githubusercontent.com/12854133/79680416-9e74fd00-81cc-11ea-91a8-5e366dfcbdb3.png)
![orig_out](https://user-images.githubusercontent.com/12854133/79680417-a16fed80-81cc-11ea-9706-3f0395ab19d3.png)
— obviously discontinuous.

This is with duplicating the initial value + 2π:
```python
    angles_ = np.append(angles, angles[0] + 2 * np.pi)
    radcorr_ = np.append(radcorr, radcorr[0])
    radial_correction_function = UnivariateSpline(angles_, radcorr_, s=smooth,
                                                  ext=3)
```
![rep1_rad](https://user-images.githubusercontent.com/12854133/79680456-ff9cd080-81cc-11ea-813f-c839a12dda1d.png)
![rep1_out](https://user-images.githubusercontent.com/12854133/79680457-01669400-81cd-11ea-9b4e-cd946fe7fa5d.png)
— looks better but actually is still discontinuous (not clearly visible at this scale) and obviously not smooth.

And this is with duplicating all points on both sides:
```python
    angles_ = np.hstack((angles - 2 * np.pi, angles, angles + 2 * np.pi))
    radcorr_ = np.hstack((radcorr, radcorr, radcorr))
    radial_correction_function = UnivariateSpline(angles_, radcorr_, s=smooth,
                                                  ext=3)
```
![qper_rad](https://user-images.githubusercontent.com/12854133/79680495-8651ad80-81cd-11ea-800c-cf06bbe6e6f2.png)
![qper_out](https://user-images.githubusercontent.com/12854133/79680497-894c9e00-81cd-11ea-9789-ea192916be28.png)
— looks continuous and smooth (openning this and the previous image and switching back and forth shows clearly how much the bottom part changes).

Since these are cubic splines, maybe adding 2–3 points (instead of all) on both sides would be enough, but this still does not look elegant and really correct.

With 
```python
    from scipy.interpolate import CubicSpline
    angles_ = np.append(angles, angles[0] + 2 * np.pi)
    radcorr_ = np.append(radcorr, radcorr[0])
    radial_correction_function = CubicSpline(angles_, radcorr_, bc_type='periodic')
```
the results actually are correct (and indistinguishable from the "quasiperiodic" `UnivariateSpline`). But `CubicSpline` does not have any smoothing control.

With
```python
    from scipy.interpolate import splrep, splev
    angles_ = np.append(angles, angles[0] + 2 * np.pi)
    radcorr_ = np.append(radcorr, radcorr[0])
    spl = splrep(angles_, radcorr_, per=True)
    def radial_correction_function(x):
        return splev(x, spl)
```
the results are again correct (and again indistinguishable). And `splrep` does have some optional “smoothing condition”, but it is different from the “smoothing factor” used in `UnivariateSpline`.

So the question is how much the `smooth` parameter in `abel.tools.circularize.circularize_image` is useful and whether it is used in reality. If not, then switching to `CubicSpline` seems to be the best solution. If allowing smoothing is actually needed, then wouldn't `splrep` be a reasonable replacement?

**Comment by stggh** [comment]
This is odd, because the radial correction function as returned from `circularize_image()` 
```python
out, sla, sc, rcf = circularize_image(img, origin=(511 + 0, 511 - 10), return_correction=True)

plt.plot(sla, sc, 'o')
plt.plot(sla, rcf(sla))
plt.xlabel(r'angle $\theta$ (radians)')
plt.ylabel(r'radial correction factor')
plt.show()
```
looks like this:
<img width="612" alt="Screen Shot 2020-04-19 at 18 39 54" src="https://user-images.githubusercontent.com/10932229/79683435-7b4e5a00-826d-11ea-91d9-845fee09e40d.png">

I will take a look at your code and points tomorrow.

**Comment by MikhailRyazanov** [comment]
Here:
```python
plt.plot(sla, rcf(sla))
```
you are plotting the spline `rcf` sampled at `sla` (very few angles), but in fact it is a continuous function and is used in `circularize` as such (applied to all angles `theta = np.arctan2(X, Y)`, where `X` and `Y` are pixel coordinates).

**Comment by MikhailRyazanov** [comment]
Well, I have done some tests with smoothing. Here is a comparison of the current implementation using `UnivariateSpline` and the periodic `splrep`, passing the same `s=smooth` to both, for various `smooth` values:
![spline_cmp](https://user-images.githubusercontent.com/12854133/79711796-1b17e200-8286-11ea-87a4-4f887943d909.png)
So it seems that they behave similarly until the smoothing threshold becomes too large.
And I should admit that this quantity is not very intuitive; as I understand, it is something like (RMS deviation)<sup>2</sup> × (number of points). Maybe we should replace `smooth` with `tol` (for “tolerance”), equal to the RMS deviation?

**Comment by stggh** [comment]
Interesting information about spline smoothing.

My graph [above](https://github.com/PyAbel/PyAbel/issues/276#issuecomment-616077858) includes the additional end knot point (repeated first data point), this is sufficient to define the continuous radial correction function from [-&pi;, &pi;], the full range required for interpolation. The range (&pi;, 3&pi;] is irrelevant, unless I am missing something? Given your track record, no doubt I am. :-(    

> very few angles

The number of radial correction data point is controlled by the angular slice width parameter `dt`. This parameter would have  a larger effect than the differences between spline methods.

**Comment by DanHickstein** [comment]
Sorry for being late to the party :)

It seems like a good idea to keep the ability to use smoothing. I'm surprised that you're getting different results from UnivariateSpline and splrep. According to this scipy page, they are just different interfaces to the same FITPACK functions: https://docs.scipy.org/doc/scipy/reference/interpolate.html

Could the differences between your plots for "current" and "splrep" be due to the glitches in "current" caused by the lack of periodic boundary conditions?

**Comment by MikhailRyazanov** [comment]
> caused by the lack of periodic boundary conditions

Exactly.

@stggh, I thought that _you_ know how this method works... :–)

Yes, the number of the points is controlled by `dr`, but they are not used for circularization directly. Instead, a spline is fitted to them, and then this spline is evaluated for each pixel's polar angle. By repeating the first data point (if it was −π, and in fact it is not), we could satisfy the boundary condition rcf(−π) = rcf(+π), but the derivatives generally would not match, and thus the “circularized” image can have a “corner” in the downward direction. (I plot the range (π, 3π] just to show the transition from “+π” to “−π”. You can consider the [0; 2π) range, which gives the same full circle, and on which the function must be smooth as well.)

We can of course use `k=1` to fit a piecewise linear function instead of a cubic spline, so it will have a “corner” at each knot, like in your plot. In practice this is fine as long as the knots are sufficiently dense, but if we use a cubic spline, it would be natural to expect it to be smooth at all angles instead of having a singular point.

**Comment by stggh** [comment]
> that you know how this method works

Obviously, not well enough :-(   Fair enough, it is good to be precise. In the end the errors in determining the radial scale factor dominates the interpolation function.

**Comment by DanHickstein** [comment]
So, if we just switch the interpolation to splrep with the periodic boundary conditions, does this solve the main problem here?

**Comment by MikhailRyazanov** [comment]
> does this solve the main problem here

As far as I can tell.

Using `s=len(angles) * tol**2` also looks reasonable and more intuitive:
![tol](https://user-images.githubusercontent.com/12854133/79829594-b1b8d180-8360-11ea-95ef-e7b51d0da8dd.png)
(the dashed lines are ±`tol`).

**Comment by DanHickstein** [comment]
Cool!

If I understand correctly, you are saying that:

1) switching to splrep with the periodic conditions completely addresses the discontinuity (title of this Issue). 

2) We uncovered another issue: the smoothing factor is not very intuitive. Empirically, it seems that the smoothing factor works consistently when we scale it as `s = len(angles) * tol**2`, where `tol` should tend to be approximately the RMS error of the points. In this case, the points are the radial correction factor, which ranges from 0 to 1. So, `tol` should range from 0 to much less than 1.

Both seem like quick and easy changes, so that's good :)

I also learned something here about how to use splines! Picking the correct smoothing factor had always seemed unnecessarily difficult.

Actually, now that I look more carefully at the docs for [splrep ](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.interpolate.splrep.html#scipy.interpolate.splrep), I see that the amount of smoothness is given by `sum((w * (y - g))**2,axis=0) <= s`, where w is the weights, y is the data, and g is the spline. So, if the weights are equal to 1 everywhere, then we are left with `sum((y-g)**2)`, which is `(number of points) * (RMS error)**2`.

They even say that the above is the case, but in a super confusing way: 

>  If the weights represent the inverse of the standard-deviation of y, then a good s value should be found in the range (m-sqrt(2*m),m+sqrt(2*m)) where m is the number of datapoints in x, y, and w.

So, they are saying that, if the weights are 1/(standard dev) then the best `s` will be somewhere around the number of data points. Which is the same thing that you are saying.

The FITPACK code also provides a confusing discussion of the smoothing factor: https://github.com/scipy/scipy/blob/master/scipy/interpolate/fitpack/curfit.f#L141

I think that the scipy documentation could use some improvement here. 

1) Basically, the docs for both [splrep ](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.splrep.html#scipy.interpolate.splrep)and [UnivariateSplite](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.UnivariateSpline.html#scipy.interpolate.UnivariateSpline) should mention something to the extent of: *"If the weights are all set to 1 (default), then the appropriate value of `s` will be somewhere near len(x)*sd**2, where is is an estimate of the standard deviation of the data points."*

2) The docs for UnivariateSpline should be changed so that they mention that the default value for the weights array (`w`) is`ones(len(x))`. This is important, because the absolute value of the weights array matters for choosing x, it's not enough to say "weights are all equal". 

I haven't seen too much discussion on the Scipy GitHub page about the spline smoothing. But there is this discussion that is somewhat related: https://github.com/scipy/scipy/issues/4975#issuecomment-112867854

**Comment by MikhailRyazanov** [comment]
I also had hard time trying to decipher the documentation, and my understanding is exactly as you describe.

I've checked for various tolerances and numbers of points that `s = len(angles) * tol**2` indeed produces RMS errors equal to `tol` (except when the function complains that “The maximal number of iterations ... has been reached”, which happens rarely, but even then the error is not much larger).

> In this case, the points are the radial correction factor, which ranges from 0 to 1. So, `tol` should range from 0 to much less than 1.

The radial correction factor is actually multiplicative. 1 means no change, 0.99 is 1% contraction, 1.01 is 1% expansion and so on.  Basically, `tol = 1 / R` should give RMS deviation not exceeding 1 pixel at radius `R`. But this deviation is of the spline correction function from the factors found at specific angles, while these factors themselves can have unpredictable errors.

**Comment by DanHickstein** [comment]
I opened an issue on scipy to see if they are interested in doc improvements: https://github.com/scipy/scipy/issues/11916

**Comment by MikhailRyazanov** [comment]
> But, if you are making `tol` more than, say, 0.1, you know that something else has gone terribly wrong.

Apparently, their understanding of “smoothing” for periodic splines also includes minimizing the variation of the spline itself:
![large_tol](https://user-images.githubusercontent.com/12854133/80041258-3454a480-84b9-11ea-9273-6cc96dfe5181.png)
In other words, if you specify `tol = 0.1`, this means that you don't care about 10% deviations, and thus you don't need any correction at all...

This makes _some_ sense, but is not obviously expected from a fitting procedure. In the second case (tol = 0.1), the fact that it was able to reduce the number of spline nodes to just one while keeping RMSE < 0.1 is understandable. But in the first case (tol = 0.01), a cubic spline with the same number of nodes could follow the data points much better. Even stranger is that without the periodic condition (`UnivariateSpline` or `splrep(..., per=False)`), it actually prefers better fitting instead of smaller spline variation:
![large_tol_np](https://user-images.githubusercontent.com/12854133/80041928-f6f11680-84ba-11ea-9f0a-5459f0d1f949.png)
I don't see in the documentation anything related to these differences in behavior with and without periodicity. Maybe they forgot to explain it, or maybe this is an implementation bug.

**Comment by DanHickstein** [comment]
> tol = 0.1, this means that you don't care about 10% deviations, and thus you don't need any correction at all...

Yes, I believe this is how it works. It's trying to provide you with the smoothest function possible that provides you with the requested error. You could probably describe your `tol` parameter as the "requested error in fit".

But yes, it is quite different from a standard fitting procedure. It's kinda like it starts with the assumption that your data is a line and the data tries to convince it otherwise. In your top plot (tol=0.01), it was only half-way convinced that your data was sinusoidal :).

But the differences between the periodic and the non-periodic boundary conditions are strange. 

What is the actual range that you are feeding the splrep? 0 to 2pi? (i'm slightly confused by your -1pi to 3 pi range - maybe you can explain that.

**Comment by MikhailRyazanov** [comment]
It is always from the first data point (about −π) to the last data point (about +π). The +π to +3π is duplicating the −π to +π range in the plots only (to see the periodic behavior).

I have [commented](https://github.com/scipy/scipy/issues/11916#issuecomment-618113080) in you SciPy issue https://github.com/scipy/scipy/issues/11916 about these strange differences (there is a minimal code example).

**Comment by DanHickstein** [comment]
> The +π to +3π is duplicating the −π to +π range in the plots only (to see the periodic behavior). 

Gotcha.

> I have commented in you SciPy issue scipy/scipy#11916 

Oh dear, what have you gotten us into! :)

**Comment by MikhailRyazanov** [comment]
Well, I think that now I understand how these splines work and what “smoothing” actually means (see https://github.com/scipy/scipy/issues/11916#issuecomment-618172615 for explanations and pictures). So my conclusion is that `scipy.interpolate.splrep` is the way to go and that using a new “RMS fitting tolerance” parameter would be better than the current unintuitive `smooth`. It can be just added, such that people can use either of them, or `smooth` can be deprecated, like in the recent `center` → `origin` change.

A draft of the parameter description:
> **tol** (_float_) – root-mean-square (RMS) fitting tolerance for the spline function. At the default zero value, the spline interpolates between the discrete scaling factors. At larger values, a smoother spline is found such that its RMS deviation from the discrete scaling factors does not exceed this number. For example, `tol=0.01` means 1% RMS tolerance for the radial scaling correction. At very large tolerances, the spline degenerates to a constant, the average of the discrete scaling factors.
> Typically, **tol** may remain zero (use interpolation), but noisy data may require some smoothing, since the found discrete scaling factors can have noticeable errors.
> To examine the relative scaling factors and how well they are represented by the spline function, use the option `return_correction=True`.

**Comment by DanHickstein** [comment]
That all sounds good to me. Probably we can switch from smooth to tol. I suppose deprecating smooth would be nice to any users. But, I doubt that many folks are using this parameter.

**Comment by MikhailRyazanov** [comment]
Done in #293.
