### ISSUE TITLE
Comparison of Abel Transform Methods / Speed benchmarks

### ISSUE THREAD

**Issue by MikhailRyazanov** [PyAbel/PyAbel#280]
We still have the [“Comparison of Abel Transform Methods”](https://pyabel.readthedocs.io/en/latest/transform_methods/comparison.html) section almost empty. What about showing some benchmarks (based on our RSI data) there?

Sustained transform speed
--------------------------------------
![transform_time](https://user-images.githubusercontent.com/12854133/80050739-b225a980-84d3-11ea-8bf8-1a80326cddfd.png)
![throughput](https://user-images.githubusercontent.com/12854133/80050766-cc5f8780-84d3-11ea-8fd9-d51d5067e358.png)

Basis-set generation
----------------------------
![basis_time](https://user-images.githubusercontent.com/12854133/80050791-d84b4980-84d3-11ea-904c-847e9fc139f4.png)

These are @stggh's timings (on 3.4 GHz i7-6700), plus my timings for rBasex (on 2.6 GHz mobile i5).

I have also written, based on our previous discussions, some recommendations about choosing the linear-algebra libraries and using the “daz” module (to address #246 at least partially).

If nobody has objections, I'll create a PR for this and ask @stggh to supplement it with rBasex timings on the same machine (I hope, you have access to it...).

**Comment by stggh** [comment]
Another good idea. Yes, I still have access to the original PC (Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz) and a slightly newer (Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz), but both only 32 GB RAM.

**Comment by MikhailRyazanov** [comment]
The amount of RAM is sufficient. :–) Is the new i7 any faster than the old one?

**Comment by stggh** [comment]
Yes, it appears so. Anaconda Python 3.8.2.
6700:
 <img width="375" alt="Screen Shot 2020-04-23 at 14 14 38" src="https://user-images.githubusercontent.com/10932229/80058575-fdd86180-856c-11ea-9c88-ae9ad4a38372.png">

9700:
 <img width="368" alt="Screen Shot 2020-04-23 at 14 14 50" src="https://user-images.githubusercontent.com/10932229/80058578-00d35200-856d-11ea-9b9d-0e916345ea65.png">

**Comment by MikhailRyazanov** [comment]
Looks like a factor of 2 for matrix operations and ~20% for all other stuff.

Now the question is: are you willing to redo all the benchmark on this new machine? As I remember, on the old one they took several days, and since the most time-consuming parts are not accelerated significantly, on the new machine the whole work will take almost as much time. On the other hand, just running rBasex benchmarks on the old machine to supplement the existing data will take at most several hours.

**Comment by stggh** [comment]
I am happy to do both. I just need to find the timing scripts.

**Comment by MikhailRyazanov** [comment]
OK, then the new CPU is more interesting.

Before you begin, let's clarify one more thing:
As the huge differences between forward and inverse transforms for `basex` suggest, the benchmarks above were probably done without using `daz` (see [here](https://github.com/PyAbel/PyAbel/pull/244#issuecomment-471854115)). Can you try to use `daz` on the new machine to see whether it helps?

**Comment by stggh** [comment]
Right yet again! With daz:
**6700** -----------------:
<img width="374" alt="Screen Shot 2020-04-23 at 15 51 02" src="https://user-images.githubusercontent.com/10932229/80064001-772a8100-857a-11ea-9b3b-f0edb4b6d66b.png">
**9700** -----------------:
<img width="371" alt="Screen Shot 2020-04-23 at 15 50 52" src="https://user-images.githubusercontent.com/10932229/80064017-7eea2580-857a-11ea-83af-c7d884f2f811.png">

**Comment by DanHickstein** [comment]
Yes, I think that it would be a very good idea to provide some information in the "Comparison of Abel Transform Methods" section. Probably, we should include updated versions of most of the plots from ours RSI paper there. We can certainly show the speed benchmarks, but I'm guessing that most users are working with a handful of relatively small images and won't care too much about speed. So, I would discuss the quality of the transform results first and then move on to the speed benchmarks. Probably we should simply adapt our manuscript to fit on this page and keep a "living version" of the comparison paper here. 

> on the old one they took several days

We may make the benchmarks set a bit easier to calculate. My guess is that we are going to want to regenerate it in the future when we make any speed changes to the methods, so we'll probably be calculating it several times.

I'm happy to drop the last point of Onion Bordas, Direct C, and Linbasex to speed up the calculation. Probably the last point of basex should be removed as well so that we don't need to generate the basis sets.

Maybe a good rule of thumb is that we should be testing the methods out to about 1e3 seconds. I can't imagine your average user wanting to wait even this long for a transform (or basis generation) to complete. 

> Looks like a factor of 2 for matrix operations and ~20% for all other stuff.

This makes sense considering the processor benchmarks. The ~20% versus 2x speedup is probably the difference between singe- and multi-core performance.

On Geekbench, the [6700](https://browser.geekbench.com/processors/1715) has a single-core score of 980 while the [9700](https://browser.geekbench.com/processors/2616) is 1220, so 24% better. But the 9700 is an 8-core rather than a 4-core, so the multi-core score is 6691 compared with 3790 (6700), so a 77% improvement.

**Comment by MikhailRyazanov** [comment]
> Maybe a good rule of thumb is that we should be testing the methods out to about 1e3 seconds. I can't imagine your average user wanting to wait even this long for a transform (or basis generation) to complete.

In the article you were bragging about the ability to transform gigapixel images. :–) I think, if @stggh wants to go as far as possibly, showing the whole range would not harm, but limiting to ~1000 s (~17 min) is fine too.

OK, I'll then commit what I currently have into a new branch in _this_ repository, such that everybody can contribute.

**Comment by DanHickstein** [comment]
> In the article you were bragging about the ability to transform gigapixel images. :–)

Damn right I was! :)  It's pretty cool that we can do that. But it's not super relevant to most users, and I feel that we've already proven our point (we should link to the manuscript from this comparison section). It doesn't seem that anything really interesting is happening to the performance scaling at really long times (except running out of memory).

> OK, I'll then commit what I currently have into a new branch in this repository

Yeah, I think this makes sense. My GitHub skills are lacking, so we've never actually made another branch in the main repo. I guess the advantage is that we can all make PRs to this new branch, and it's okay it each PR leaves the docs in an embarrassing state? Otherwise we can just make PRs to the main branch. I guess the disadvantage is that each PR needs to leave the docs looking acceptable for public consumption. Currently, that comparison page isn't helping anyone, so it's hard to imagine that any PR could make it any worse :)

**Comment by DanHickstein** [comment]
I guess the disadvantage of making a new branch is that the two branches could get out of sync and there would be some additional work merging the feature-branch back into the main branch. Probably a non-issue when the branch is dedicated to working with a single doc file, since there shouldn't be conflicts.

**Comment by stggh** [comment]
> On Geekbench, the 6700 has a single-core score of 980 while the 9700 is 1220, so 24% better. But the 9700 is an 8-core rather than a 4-core, so the multi-core score is 6691 compared with 3790 (6700), so a 77% improvement.

Confusingly, according to `lscpu` my systems are quite similar:
```
[etalon:.+k/Fig_benchmark]$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           94
Model name:                      Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Stepping:                        3
CPU MHz:                         800.561
CPU max MHz:                     4000.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6799.81
Virtualisation:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        8 MiB
```

```
[Gibbo:/home/stg121]$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Stepping:                        13
CPU MHz:                         1000.017
CPU max MHz:                     4700.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6000.00
Virtualisation:                  VT-x
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        2 MiB
L3 cache:                        12 MiB
```

I don't game :-(. The choice of system is limited by ANU purchasing policies, i.e. Dell PCs

`AbelTiming()` has been updated since the PyAbelPaper timings. Are you panning to include an updated `pyabel-timing.py` in the branch?

**Comment by MikhailRyazanov** [comment]
Do you mean `pyabel-timing.py` from PyAbelPaper? I thought that it should work with the current version, but I need to check...

> we've never actually made another branch in the main repo

We currently have some strange https://github.com/PyAbel/PyAbel/tree/readme_update (I have an impression that it was accidentally created by me instead of merging into master). :–)

But basically the idea is to have a branch like Pyabel:comparison, to which we all can commit (and pull from it each other's commits to our local repositories), and then create a PR PyAbel:master ← Pyabel:comparison. This should build “embarassing” docs for that PR as usual, without changing https://pyabel.readthedocs.io/en/latest/, which is built from PyAbel:master.

**Comment by stggh** [comment]
> `pyabel-timing.py` 

Yes. I had added the `rbasex` method, and am running it on both PCs, but just wanted to check.

**Comment by MikhailRyazanov** [comment]
So if you have a version that works, I will leave it to you to commit (with the new results).

Let's wait until @DanHickstein finishes with #281, since it has important corrections to the failing docs build.

**Comment by DanHickstein** [comment]
> Confusingly, according to lscpu my systems are quite similar:

You also need to look at the "Threads per core" number, which is 2 for the 6700 and 1 for the 9700. The 6700 has Hyperthreading, so it's basically lying about actually having 8 cores. It really has 4 cores + 2 threads per core. The 9700 doesn't have hyperthreading, so it's an honest 8-core. They've apparently moved Hyperthreading to i9 only. https://www.pcworld.com/article/3311519/intel-9th-gen-core-i7-lost-hyper-threading.html  I'm not a gamer either, but just envious of their sweet processors :).

> We currently have some strange https://github.com/PyAbel/PyAbel/tree/readme_update (I have an impression that it was accidentally created by me instead of merging into master). :–)

Yeah, probably you created a branch on the main repo thinking that you were on your own repo. I've done something similar before.

> But basically the idea is to have a branch like Pyabel:comparison, to which we all can commit (and pull from it each other's commits to our local repositories), and then create a PR PyAbel:master ← Pyabel:comparison. 

Wouldn't we still want to use PRs to make changes to the new branch? PRs are nice, because they provide a space for documenting the reasons behind code changes. 

I don't think that we really *need* to create a second branch to do this. But, creating other branches is really important for working on major (compatibility breaking) versions. So, it seems like a good idea for us to learn how to deal with other branches in the main repo and how to merge them back into the main branch.

So yeah, let's make a new branch and work on the comparison doc.

**Comment by MikhailRyazanov** [comment]
OK, after #283 the “Comparison” looks very nice, so I'm closing this issue.

**Comment by DanHickstein** [comment]
Sweet! Thanks for cleaning up these issues :)
