### ISSUE TITLE
Use quadrants is ignored

### ISSUE THREAD

**Issue by leon-vv** [PyAbel/PyAbel#284]
Dear all, thanks for this great project.

```
Q0, Q1, Q2, Q3 = tools.symmetry.get_image_quadrants(
                         self.IM, reorient=True,
                         symmetry_axis=self._symmetry_axis,
                         symmetrize_method=self._symmetrize_method)
```
The `use_quadrants` variable is not passed to `get_image_quadrants(...)`. This is a bug right?

**Comment by stggh** [comment]
Hi @leon-vv thanks for playing with PyAbel.

> The use_quadrants variable is not passed to get_image_quadrants(...). This is a bug right?

Yes, this is a significant bug!  

Please feel free to submit a PR, if you are comfortable with the process. See [CONTRIBUTING.rst](https://github.com/PyAbel/PyAbel/blob/master/CONTRIBUTING.rst). Otherwise, we will make the PR. The change is the `use_quandants` parameter, in `abel.transform.py` as you state:
```python
       # split image into quadrants
        Q0, Q1, Q2, Q3 = tools.symmetry.get_image_quadrants(
                         self.IM, reorient=True,
                         use_quadrants=self._use_quadrants,
                         symmetry_axis=self._symmetry_axis,
                         symmetrize_method=self._symmetrize_method)
```

Thanks very much for finding this.

**Comment by DanHickstein** [comment]
Thanks for catching this!

**Comment by leon-vv** [comment]
No worries, I'm glad I've been able to contribute

**Comment by DanHickstein** [comment]
#287 should take care of this, so closing this issue. Thanks again!
