### ISSUE TITLE
rBasex goes bonkers for order >20

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#286]
Not certain if this should be made as a new issue or not, but it is sort of in the vein of this thread.

I have been attempting to use the rbasex implementation to invert some above threshold ionization (ATI) data that requires a very high order. I have found that when the order exceeds 20 (or 21 for odds) their is a sharp change in the noise.

 The figure below shows an example of this problem. You can produce the same result with the rbasex "beam block" example. The cutoff is always at order 20 (or 21 for odd). As the order increase the problem only gets worse. If this is just a limit of rBasex then it should probably be mentioned in the documentation that their is a maximum order that is usable.

![OrderCompare](https://user-images.githubusercontent.com/9374644/80268769-f2259180-8677-11ea-81f8-cc6cc381f310.png)

_Originally posted by @talbert48 in https://github.com/PyAbel/PyAbel/issues/264#issuecomment-619303418_

@MikhailRyazanov replied:

Can you try other “polar” methods (lin-BASEX, pBasex, POP) to see how they behave with very high orders?

And, before going into computational details, is ATI reasonably described in terms of Legendre polynomials? I have no experience with it, but from the few examples that I've read, it seems to be non-perturbative and involve strong interference between many channels.

**Comment by DanHickstein** [comment]
Can we run rBasex on a simpler example and see what the behavior is for n<21 and n>21? That might rule out the ATI-specific issues that @MikhailRyazanov proposes.

**Comment by MikhailRyazanov** [comment]
> might rule out the ATI-specific issues

I didn't mean that the observed rBasex behavior is specific to that particular example, but rather that if ATI is in general not describable by a finite number of spherical harmonics, then using a method based on such assumptions is not a good idea in principle.

I can say about high orders in rBasex, and ` abel.tools.vmi.Distributions` as well, that since they use cos<sup>_n_</sup> θ basis, which is not orthogonal (in fact, [very badly](https://en.wikipedia.org/wiki/Hilbert_matrix)), they must have numerical stability problems for sufficiently high orders, but the exact numbers should depend on computational details and on the image radius. I have mentioned this several times, but maybe not in the documentation?

Since Legendre polynomial are orthogonal, I _expect_ that they might be more numerically stable, thus I suggest to check how the other methods, which use them, behave. However, I did not see such examples in the literature, so my expectations might be wrong (that is, maybe all the methods misbehave at high orders), or there are no physically reasonable problems involving exactly _n_ = 22 or so, and thus nobody cared to address that.

**Comment by DanHickstein** [comment]
Thanks @MikhailRyazanov. So, you are saying

1. We should expect rBasex to go crazy at some reasonably high order. The exact order will depend on the size of the image and maybe what the data is. This is because the basis set is not orthogonal. 

2. For ATI, users who want a radial+angular-basis-set-based transform method might need to investigate methods based on Legendre polynomials, like linbasex. (or pBasex/POP, which are not yet implemented in PyAbel.)

> they must have numerical stability problems for sufficiently high orders, but the exact numbers should depend on computational details and on the image radius. I have mentioned this several times, but maybe not in the documentation?

Yes, I do remember you mentioning that the cosine basis sets are not orthogonal. But, you bring up a good point about the documentation. I opened #289 to discuss how we can make it easier for users to get the right docs for the transform methods. 

I'm curious what @talbert48 wants from the Abel transform? Is it sufficient to just use one of the methods like normal basex that doesn't make as many assumptions about the ATI data?

**Comment by MikhailRyazanov** [comment]
> For ATI, users who want a radial+angular-basis-set-based transform method might need to investigate methods based on Legendre polynomials, like linbasex.

These are actually two separate questions:
1. To investigate how methods based on Legendre polynomials behave for high angular orders.
2. Is it reasonable at all to analyze ATI data in terms of angular components? Basically, _n_ = 22 means that exactly 11 photons are involved, but as I understand, the number of photons in ATI can be arbitrarily large (with decreasing probabilities), so not particular _n_ will be sufficient to analyze the data correctly.

**Comment by talbert48** [comment]
I have tried numerous ATI data sets with rbasex and pbasex, both have problems as the order of the Legendre polynomials increases. rbasex fails as soon as you hit order = 22, pbasex is a lot more gradual, you don't see a sharp change in the noise, but rather as the order increases the noise gets increasing noticeable, especially along the symmetry axis, up to order 30 pbasex is reasonable, and arguably even up to order 40, however if the order goes too much more past that it gets bad. 

For pbasex, going to order 40 is perhaps overkill in any reasonable situation. ATI is problematic, it is highly non-perturbative and you can very easily generate electrons with energies in excess of 100 eV with infrared lasers. Which if you think in terms of photons gives photon numbers on the order of 100 photons. My experience has been that with pBasex the radial and angular distributions converge by order 30-40 and little is gained going past that. Orders larger than 20 are important, their are interferences missing that are seen as early as order 30 in pbasex that are not seen at order 20.

I have been interested in rbasex due to the substantial increase in speed. pBasex on a large image ( 1761 x 1761 px) and orders up to 40 is incredibly slow and requires large amounts of RAM. Basex works great for these data sets, but we are interested in the behavior along the symmetry axis, which for basex has appreciable centerline noise and is not particularly useful. Linbasex works up to order 30, but the results are overly smoothed, I haven't had much time to look closely at this smoothing, it may be easily resolved, but I'll look at it over the next few days.

The question, as previously stated by @MikhailRyazanov, is it reasonable to analyze ATI data using these angular components still stands. I'm not sure and I'll have to do some reading. 

If we simplify the data and use the image from the "rbasex beam block" example (removing the beam block) we see the sharp change at order 22. The image size in this example is significantly smaller than my ATI data (radius of 150 vs 880), but still exhibits the same behavior at the same order. Any order larger than 22 will exhibit this noise, it only gets worse.

![Figure_1](https://user-images.githubusercontent.com/9374644/80335536-91868800-8822-11ea-83f6-f01bf07c2476.png)

Whether this is worth looking into too closely is debatable. The subset of people that care about these very high orders is presumably a very small subset, and it is not clear whether this approach is even reasonable for such datasets.

**Comment by MikhailRyazanov** [comment]
@talbert48, thanks for the information!

In the situations when you really have 100 photons, you will need at least 100 terms in the angular expansion, or, with interference, even 200. This means that there must be at least as many pixels along a quarter circumference, so for radii ≲ 100 pixels all these angular terms cannot be extracted anyway, and for radii ≲ 200 pixels all the input-image noise will be extracted. In general, for a _complete_ basis set, it does not matter whether it is “polar”, as in pBasex, or “Cartesian” as in BASEX and other general methods; the transform results _must_ be the same. In particular, the centerline noise will be the same in both methods.

This is also directly related to the question how do you analyze the transform results. If you have some model, then you can just fit it directly to the “noisier” BASEX results. Since both BASEX and rBasex are linear, the fit results must also be the same (on average); the only difference being that rBasex (imagining that it works) will do smoothing before your fitting, but for BASEX, your model will impose smoothing.

I think that by more careful computations it should be possible to make higher orders more numerically stable, but as pBasex suggests, not much higher. And this requires deep analysis, so I will not be able to work on this in the near future.

A brute-force solution would be to use higher-precision floating-point numbers. Unfortunately, doing so in Python does not looks staightforward, but if you are really interested, you can reimplement the needed parts of the method in C++ and use the available quadruple-precision (or even arbitrary-precision) libraries. I suspect that the main source of the observed noise comes from the extraction of the cos<sup>_n_</sup> θ radial distributions (done by `abel.tools.vmi.Distributions`), and if this can be done better, then everything else should work reasonably well, since the transform itself is better-conditioned, and the addition of cosine powers to create the output image is also numerically stable to higher orders.

**Comment by DanHickstein** [comment]
Re-visiting this issue, it seems that we have now mentioned in the documentation that rBasex may now work well for orders above about 15. Actually making rBasex more stable for higher orders seems like something that we're not going to work on in the near future. So, I'm going to close this issue. Feel free to re-open if there are things that still need action.
