### ISSUE TITLE
Crop in only 1 axis

### ISSUE THREAD

**Issue by Mobbybobby** [PyAbel/PyAbel#296]
Hi,

your crop function always crops in both axis, even when the image is centered is with respect to only one axis.

I fixed it for my case:

center.py line 264:
```ruby
 elif crop == 'valid_region':
        # crop to region containing data
        shift0, shift1 = (None, None)
        if isinstance(axes, int):
            if axes == 0 and delta0 != 0:
                shift0 = 1 + int(np.abs(delta0))
                return centered_data[shift0:-shift0, :]
            elif axes == 1 and delta1 != 0:
                shift1 = 1 + int(np.abs(delta1))
                return centered_data[:, shift1:-shift1]
            else:
                raise ValueError("axes value not 0, or 1")
        else:
            if delta0 != 0:
                shift0 = 1 + int(np.abs(delta0))
            if delta1 != 0:
                shift1 = 1 + int(np.abs(delta1))
            return centered_data[shift0:-shift0, shift1:-shift1]
    else:
        raise ValueError("Invalid crop method!!")
```

I hope this helps you or other users.

Thanks and great package!

Mobby

**Comment by DanHickstein** [comment]
Hi Mobby,

Thanks for the suggestion! I think that this makes sense. If the user specifies `axis=1`, then they are still required to enter some value for the center row in the `origin` keyword argument. And, currently, the image will still be cropped using this nonsense value.

The code the you have seems good to me. Are there additional suggestions from @MikhailRyazanov or @stggh?

@Mobbybobby, can you make a Pull Request for this change?

**Comment by stggh** [comment]
A good point!  

We can use the PR to further review the `set_center` code.  

In the block above, `crop == maintain_data`  the `area` reassignment does not look right:

```python
        area = container[:, :]
        if shift0:
            if delta0 > 0:
                area = area[:-shift0, :]
            else:
                area = area[shift0:, :]
        if shift1:
            if delta1 > 0:
                area = area[:, :-shift1]
            else:
                area = area[:, shift1:]
        area[:, :] = data[:, :]
        data = container
```

**Comment by Mobbybobby** [comment]
Yes, I only fixed it for valid_region at the moment since it is the method i need. I never done a Pull request sorry. I usually don't work with GitHub.

**Comment by stggh** [comment]
@MikhailRyazanov of course I should have included you in the "_will no doubt have the solution_" for the all files lines have changed PR  #298. The torment of Windows OS.

**Comment by MikhailRyazanov** [comment]
@DanHickstein,
> If the user specifies axis=1, then they are still required to enter some value for the center row in the origin keyword argument. And, currently, the image will still be cropped using this nonsense value.

I remember than when I was doing the “center”/“origin” cleanup, I saw some problems with centering wrt only one axis, but now I can't easily find that discussion...

Anyway, for this particular function, it would be the best to ignore the unneeded coordinate completely, such that `(row, None)` or `(None, col)` can be given instead of “some value”. This can be also allowed even for `axes=(0, 1)` by ignoring `None` coordinates. Then manual 1-dimensional centering can be done simply by passing `(row, None)` or `(None, col)` without specifying the axis explicitly.

**Comment by DanHickstein** [comment]
> Then manual 1-dimensional centering can be done simply by passing (row, None) or (None, col) without specifying the axis explicitly.

Yes, this seems like a great way to simplify the function. Just to be clear, you're saying that we can completely get rid of the `axes` keyword, right?

**Comment by MikhailRyazanov** [comment]
Completely removing the `axes` argument will require to revise `center_image()`, since now it does
https://github.com/PyAbel/PyAbel/blob/f110ba34ad1e8e6bc920c40b402a3963527064b2/abel/tools/center.py#L153-L159
But we can change the `set_center()` logic as described, which will be backward-compatible and localized.

I think, it would be nice to eventually add the `axes` argument to the `find_origin()` function (and its underlying methods), because now it does unnecessary work for those who need only one axis (and some methods even fail when there is no symmetry wrt the other axis). Then it could be made to return `(row, None)` or `(None, col)`, which can be passes to `set_center()`, and at that point `set_center()` will not need its `axes` at all.

**Comment by MikhailRyazanov** [comment]
PR #302 can handle `(row, None)` or `(None, col)` and does not break when centering already centered images.
Adding `axes` to `find_origin()` probably deserves a separate issue.

**Comment by MikhailRyazanov** [comment]
@Mobbybobby, could you please test whether the [new code](https://github.com/PyAbel/PyAbel/blob/66c53f5d0fb17bff784084b65ed0b071c97fbdaa/abel/tools/center.py) from PR #302 works correctly in your use cases?

**Comment by Mobbybobby** [comment]
> @Mobbybobby, could you please test whether the [new code](https://github.com/PyAbel/PyAbel/blob/66c53f5d0fb17bff784084b65ed0b071c97fbdaa/abel/tools/center.py) from PR #302 works correctly in your use cases?

I did. It seems to work fine:

Initial data:
![pre](https://user-images.githubusercontent.com/62440427/91957540-74991e80-ed06-11ea-830f-65ca37ee32e6.png)

`phase = abel.tools.center.center_image(phase, method='convolution', crop='valid_region', axes=0)`

centered data:
![post](https://user-images.githubusercontent.com/62440427/91957601-8aa6df00-ed06-11ea-875e-02520e3d6482.png)

**Comment by MikhailRyazanov** [comment]
> I did. It seems to work fine

Great, thank you! I'll then merge that PR as soon as @DanHickstein approves it.

**Comment by MikhailRyazanov** [comment]
OK, #302 is merged, so we can close this now.
