### ISSUE TITLE
Windows or Mingw or cygwin installation?

### ISSUE THREAD

**Issue by cyanacobalamin** [PyAbel/PyAbel#315]
Hello,
First of all, I congratulate the developers for this fine piece of work and thank them for sharing it. I am interested in trying out PyAbel. Unfortunately, I am restricted to Windows only. I searched for instructions but perhaps I am missing them. Can someone point me to a resource or be kind enough to guide me with step-by-step installation instructions either directly for Windows or under MinGW or Cygwin? I must mention I have little to no background with unix/shell scripting commands. So, I'll be grateful if those responding will take care to be explicit with the commands to execute. 

Thanks much!

**Comment by DanHickstein** [comment]
Hi there!

PyAbel is Python code, so it works equally well on Windows, Mac, and Linux. If you don't already have python installed, I'd recommend that you get Anaconda, since it comes with lots of the common scientific packages: https://www.anaconda.com/products/individual#Downloads

Then, you can go to your start menu, type "Anaconda Prompt", right click, "Open as Administrator". Navigate to wherever you downloaded PyAbel (using the "cd" command). Now, type
```
python setup.py install
```

Now, you have PyAbel installed. 

Next, to actually do something, go to the start menu and type "spyder" to open Spyder, which is a nice editor for python code. Open one of the example files in the pyabel examples directory. press the run button on the top of the screen to run the example.

Let me know if that gets you started.

**Comment by DanHickstein** [comment]
@stggh and @MikhailRyazanov: Probably we should include more specific information in the readme for how to get going.

**Comment by cyanacobalamin** [comment]
Thank you Dan! This is great. I apologize for not mentioning that I already have Cygwin and MingW installed. I see I have python and numpy installed as well, but perhaps not scipy and matplotlib as is required. I have a plotting utility, gnuplot, if that helps. Would you suggest just getting scipy and matplotlib within cygwin and will the commands work similarly as in the examples OR will it be better to just get annaconda?  (Space on my SSD is a bit of a concern, hence asking)

**Comment by cyanacobalamin** [comment]
Hi Dan, I installed Anaconda (took up 5GB) and I could run an example using Spyder and can view the plot. I have two questions:

1. How do I access the numerical values of 'x' and the reconstructed 'f(x)' ?  Let's take the example of  reconstructing the gaussian using basex, i.e. example_basex_gaussian.py. I see a "Variable Explorer" in spyder but I'm not able to locate the pair of x, f(x)--reconstructed values. Also, are these values going to be in double-precision?

2. Instead of providing Pyabel an image or an analytical function for the Forward Abel transform, is it possible to have pyAbel read "x" and "AbelTran(x)" from a datafile and output  "x" and "InvAbel(x)" in another datafile? If yes, can you tell me how?

**Comment by DanHickstein** [comment]
Great! Sounds like you are up and running!

1. in the example_basex_gaussian, `ref.r` is the x values, `ref.abel` is the input to the inverse transform, and `recon` is the reconstructed values. You should see those in the variable explorer.

2.  The inverse abel transform functions just take "AbelTran(x)", you don't need to provide x. So, you'll just need to load your data as a numpy array and pass it to the `abel.basex.basex_transform` function, just like in that example. You can load a lot of datafiles using `np.loadtxt('path/to/filename')` and save using `np.savetxt()`. Try googling those a bit and see what you can come up with. If you get stuck, I'll have more time to help later. 

Thanks,

Dan

**Comment by MikhailRyazanov** [comment]
@DanHickstein
> Probably we should include more specific information in the readme for how to get going.

Probably we should release more often, so that people can just do `pip install PyAbel`. ;–)
And maybe give some link(s) about Python itself and how to install it (besides Anaconda)... I don't think that we can and should teach Python to people who don't know anything about it and just want to use Abel transforms (in the meantime I'm working on a new GUI, which hopefully will allow people to analyze their data without bothering about internals).

**Comment by cyanacobalamin** [comment]
Thanks Guys!

**Comment by DanHickstein** [comment]
> Thanks Guys!

Great! Glad we could help. Please let us know how it goes and if you have any more questions.

> Probably we should release more often, so that people can just do pip install PyAbel. ;–)

Yes, we should release way more often - not question there. But still, I imagine that there is a user group who has no previous Python or command-line knowledge but would still like to Abel transform some data. This group basically wants a stand-alone GUI-based program. Making a nicer GUI is a big step in this process. 

But, we also need to include the basic information about how to install PyAbel. An experienced Python user knows that it means to "pip install pyabel", but a new Anaconda user on Windows needs to know how to open the Python Prompt thing so that they can install PyAbel. Anyway, I'll make a PR with some proposed edits to the Readme.

**Comment by MikhailRyazanov** [comment]
@DanHickstein, yes, I meant that we should add some links to tutorials for new users — such guides do exist, so we don't need to write this stuff ourselves, just find what to point to. Please make a PR or an issue when we can discuss this...
