### ISSUE TITLE
Conda package is broken for Python 3.9

### ISSUE THREAD

**Issue by oobie2142** [PyAbel/PyAbel#329]
On Linux Mint 20.2 with Python 3.9.7 trying to import package
`
33908 illegal hardware instruction (core dumped)  python -c 'import IPython; IPython.terminal.ipapp.launch_new_instance()'
`
Not sure if the Python 3.8 work around applies to this situation, but will I need to update some flags to get this to work?

**Comment by stggh** [comment]
Hi @oobie2142 thanks for playing with `PyAbel`. 

I run Ubuntu 21.10, python 3.9.7, and have not experienced any `PyAbel` installation issues:
```python
Gibbo:/home/stg121]$ which python
/usr/bin/python
[Gibbo:/home/stg121]$ python -V
Python 3.9.7
[Gibbo:/home/stg121]$ 
```
Using the install command:  `python setup.py install --user`

I have also tried using the latest conda, also python 3:
```python
/home/stg121/anaconda3/bin/python
(base) [Gibbo:.+l/PyAbel-master]$ python -V
Python 3.9.7
```
`PyAbel` install also without error.


From the error message, there may be something wrong with your conda installation. Perhaps, try removing it and reinstall?

@MikhailRyazanov is more knowledgeable on these matters, and will probably provide a definitive solution.

**Comment by MikhailRyazanov** [comment]
I guess, it's the same error as in #320, so we probably should close this issue as a duplicate and continue the discussion there.

My understanding is that the problem appears when user's CPU is different from the CPU on the server that builds the Conda package, so some users (like @stggh) don't see it at all, but for some users it completely breaks the whole package. And because this is caused by an optimization flag that is merely supposed to _hopefully_ speed up just one slow (an thus perhaps not very popular) method, I'm inclined to simply remove that flag. I'm cleaning up our pending PRs and then will try to see what can be done with this...

**Comment by oobie2142** [comment]
Thanks @MikhailRyazanov I will close and move over to comment in #320
