### ISSUE TITLE
Update release checklist in contributing.rst

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#334]
We should make a better release checklist in this section of the CONTRIBUTING.rst file: https://github.com/PyAbel/PyAbel/blob/master/CONTRIBUTING.rst#releasing-on-pypi

Something like:
**Releasing a new version**

First, make a PR that does the following:
- increment the version in `abel/_version.py`
- Update the Changelog so that all of the "unreleased" changes are now part of the version. 
- Use the changelog to write version release notes that can be included as a comment in the PR and will be used later.
- Update copyright years in `doc/conf.py`

After the PR is merged:
- Press the "Draft New Release" button on the releases page. 
- Copy and paste the release notes from the PR into the release notes. 
- Release it!
- PyAbel should be automatically released on PyPi (see PR #161). Check that the new version is on [PyPi](https://pypi.org/project/PyAbel/).
- Check that the new docs are on [Readthedocs.org.](https://pyabel.readthedocs.io/en/v0.8.5/index.html)
- Check that the new version is on Zenodo: https://zenodo.org/record/5888391#.Yerecn3MKgw
Increment the version number in abel/_version.py.
- A bot should automatically make a PR on the conda-forge repo (takes a while). This will need to be manually merged: https://github.com/conda-forge/pyabel-feedstock

https://github.com/PyAbel/PyAbel/issues/334

**Comment by MikhailRyazanov** [comment]
Since all theses instructions are for maintainers only, rather than for regular contributors, maybe there is a better place to keep them? Or at least reorganize CONTRIBUTING such that all this stuff is collected at the bottom in a separate section, marked such that potentials contributors don't need to care about it...

Regarding details:
* Maybe suggest to put the expected release date in the changelog, and if the actual date differs, then update it just before merging the PR.
* "Draft New Release" also needs to create an appropriate tag. It does suggest to do so, but writing this down would be useful, with a reminder to check that it matches the new version number (copy/paste?).
* I think, it might be better to show the links explicitly and make sure that they are correct (currently yours point at v0.8.5), like:
  * ... PyPI: https://pypi.org/project/PyAbel/
  * ... Readthedocs.org: https://readthedocs.org/projects/pyabel/versions/
  * ... Zenodo: https://zenodo.org/search?page=1&size=20&q=conceptrecid:594858&all_versions&sort=-version
    (this one looks strange — is there a human-readable link for “all PyAbel versions” or “latest PyAbel version”?)
* For conda, perhaps add that after merging the PR at conda-forge, check https://anaconda.org/conda-forge/pyabel/files to make sure that the packages are released.

**Comment by DanHickstein** [comment]
I think this can be closed since it was addressed in #360. Thanks Mikhail!
