### ISSUE TITLE
Test failure in v0.8.5

### ISSUE THREAD

**Issue by bwohlberg** [PyAbel/PyAbel#335]
One of the tests is failing in release v0.8.5:
```
$ pytest --pyargs abel
============================= test session starts ==============================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
```
...
```
tests/test_dasch_methods.py ..F..                                        [ 20%]
```
...
```
=================================== FAILURES ===================================
____________________ test_dasch_deconvolution_array_sources ____________________

    def test_dasch_deconvolution_array_sources():
        im = abel.tools.analytical.SampleImage(101).image
        q = abel.tools.symmetry.get_image_quadrants(im)[0]
    
        # clean up any old deconvolution array files
        fn = 'three_point_basis_{}.npy'.format(q.shape[0])
        if os.path.exists(fn):
            os.system('rm {}'.format(fn))
    
        gb = abel.dasch.three_point_transform(q)
>       np.testing.assert_equal(abel.dasch._source, 'generated')
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: 'file'
E        DESIRED: 'generated'
```

**Comment by MikhailRyazanov** [comment]
Thanks for reporting!

This is related to #327, which changed the default `basis_dir` from `'.'` to another location, but this particular test still tries to delete its files from the current working directory. When working on that change, I forgot to rerun *all* unit tests locally, and our CI tests pass because they run on a clean system...

I need to go through the unit-test files and make sure that they all use the `tests/data` subdirectory and don't interfere with the system cache...

However, this shouldn't affect the operation of PyAbel itself.

**Comment by MikhailRyazanov** [comment]
PR #336 should solve this. @bwohlberg, could you please test it?

**Comment by bwohlberg** [comment]
All tests pass in the branch for PR #336.

**Comment by MikhailRyazanov** [comment]
Thanks!

**Comment by MikhailRyazanov** [comment]
OK, I'm closing this as solved.
