### ISSUE TITLE
README diagram suggestions

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#350]
We recently changed the diagram in the README from this: 
![image](https://user-images.githubusercontent.com/1107796/161462379-38bd3470-97f6-4370-9c1f-5bcd11fec53f.png)

To this:
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/1107796/161462457-5ac05d73-c3cf-4eff-8482-fa19dbb16af8.png">

I love that we are switching to a tiny svg file and that this allows the documentation to be built offline (thanks @MikhailRyazanov!!). But, I prefer the appearance of the first figure. I have the following suggestions to make the svg look better.

1. Change from serif to sans-serif font. Figures typically look better with sans-serif. 
2. Increase the width of the z, r, and y axes lines. Aesthetically I think that this looks better.
3. Make the z-axis on the 2D projection lighter green. I like the very bright green of the original. 
4. Even though I see that it makes sense to use 2D objects to represent the y and z axes of the 2D projection, I think that it looks prettier with the 3D axes. 
5. If 2D axes are kept for the 2D projection, I think that the z axis should still be in front of the projection data. Again, mainly for aesthetics. 
6. Does the projection in the SVG figure look qualitatively different than the original figure? To me, is seems that the "inside edge" looks a bit sharper. 
7. The angle of the original does a worse job of showing the inside of the 3D object, but it produces an image that has less wasted space above the 3D object and below the 2D projection. 
8. I think that the z axis should be aligned with one of the gridlines instead of between two of them. 
9. I prefer the way the grid looks in the original: finer grid, lighter gray gridlines, and lighter gray background. 

Okay, that's what I got. Sorry to nitpick. Accept or reject those as you see fit. 

(MR edit: I've converted the list to numbered, for referencing.)

**Comment by DanHickstein** [comment]
Oh, one more thing, on my screen the figure looks a bit small, and should probably be made larger in the readme. Also, should it be centered?

<img width="882" alt="image" src="https://user-images.githubusercontent.com/1107796/161463600-19fd77cc-7503-479c-8bfe-e301031cc86b.png">

**Comment by MikhailRyazanov** [comment]
OK, I was surprised that my *draft* figure was accepted without any discussion, :–) so let's finally try to improve it...

Point by point:

1. Already done in #349 (8b5d93a). This was my coding error in SVG font specifications (the PDF font has been always correct because it is my default system font). Can you please confirm that the new SVG renders correctly in macOS browsers?
2. See 8 below.
3. I was trying to maintain reasonable contrast, and even now the *z* axis is brighter than the other two:
![overview_bw](https://user-images.githubusercontent.com/12854133/161608815-63450d4c-ff54-42bb-ab6c-8949b4e1f829.png)
But I can make it lighter to see whether it would look better.
4. Yes, the intention was to show 2D in 2D. Implementing proper 3D clipping might need some extra effort but is doable, I can try.
5. The idea was to demonstrate that the object is really projected “on” the detector plane. However, drawing the coordinates over it would be fine too.
6. Since drawing a real paraboloid / shaded parabola in SVG is not trivial, I in fact used a truncated very elongated ellipsoid / ellipse (in the limit, this would give the original shapes). The Abel projection in this case is analytic and depends only on the “stretched radius” (rigorously, it is an appropriately stretched projection of a spherical shell), so it is easily drawn by filling the ellipse with a “radial gradient”. It indeed has both sharp edges, see the [plot of StepAnalytical](https://pyabel.readthedocs.io/en/latest/abel.html#abel.tools.analytical.StepAnalytical). I guess, your figure used a relatively low-resolution numerical image, antialiased by the renderer, so it looked smoother than it should.
7. I was trying to show more volume/depth, but it can be decreased, of course. The problem here is that your render uses noticeable perspective, but implementing it properly in SVG would require much more effort than the simulated parallel projection. Notice that the *y* axes in both images point in very similar directions, but the upper part of your render is much more horizontal. If I bring the “overall angle” closer to yours, unfortunately the whole image will look much flatter. Though, maybe it would be fine, I can try.
8. The idea here was to show that we use pixel-centered coordinates. This also determines that the axes are thinner and the grig (which is supposed to demonstrate the pixel grid) is coarser. If this doesn't sound important, I can easily make the grid finer and the axes thicker and aligned with the grid.
9. See 8 above. The colors can be adjusted, of course.

Tell me what you think, and I'll prepare an updated version!

About centering and size:

GitHub ignores image alignment (see https://github.com/github/markup/issues/163). I can add `:align: center` back (and it is currently used in the built documentation), but this is unlikely to help (although PyPI might respect it). We can also try to use raw HTML, as suggested in the linked discussion, but I consider this less desirable and more fragile. By the way, should we also center the example output or not?

I think, `:width:` is also ignored by GitHub, but I can just make the image larger and then scale it down in other places (if it doesn't fit automatically).

**Comment by DanHickstein** [comment]
Thanks for making the changes!

For some reason, the figure you included is in grayscale.

1. Yes, the font looks good now!
2. Ah, I see what you mean about the pixel-center grid. I don't think that this figure needs to communicate everything about our implementation of Abel transforms. I'd pick a prettier figure over showing that our implementation is center-pixel-at-center.
3. Yeah, I think that lighter would be nice.
4. Okay, if you want to leave the 2D axes 2D, that is okay. 
5. I think that it just looks nicer with the z-axis in front of  the image, but I see what you mean.
6. Okay, what you are saying about the projection makes sense to me.
7. Ok.

Okay, if it's tough to center on github then we don't need to worry about it. Minor issue, and if it looks centered in the docs, then this is fine. We should prioritize the readme to look good in the docs, and as long as it doesn't look completely terrible on GitHub, then this is fine.

**Comment by MikhailRyazanov** [comment]
I haven't made any changes yet, waiting for your reply first! :–) The figure in grayscale is the same SVG figure, simply converted to grayscale PNG to illustrate the lightness issues. I don't think that we have any users with total color blindness, so the green axis of any lightness will be distinguishable from the gray background, but I just generally prefer similar items to be perceptually similar (compare the “Forward” and “Inverse” arrows, for example)... However, I'll try to make the *z* axis lighter and place the axes over the image, so they will be more visible.

**Comment by DanHickstein** [comment]
Wow! This new version looks awesome!

Should the z, y, and r labels be boldface to make them a little easier to see? Otherwise I think this is great.

**Comment by MikhailRyazanov** [comment]
> Should the z, y, and r labels be boldface to make them a little easier to see?

Let's try:
![overview_bold_ax](https://user-images.githubusercontent.com/12854133/161860744-1aadd7a3-da7d-424e-bb4f-ff7bf3921633.svg)

And, just in case, with boldface “transforms” as well (hopefully, the text fits correctly in all browsers/systems — I don't want to make the arrows even longer):
![overview_bold](https://user-images.githubusercontent.com/12854133/161860806-6a99fbe9-d514-44a8-99dc-6be7397a5907.svg)

**Comment by DanHickstein** [comment]
Looks good to me! I like the bold axes labels. I think that I prefer the bold labels on the abel transform arrows too.

Thanks for making the changes. looks great!

**Comment by MikhailRyazanov** [comment]
All done in #352!
