### ISSUE TITLE
Discussion on a consistant naming scheme for different implementations

### ISSUE THREAD

**Issue by rth** [PyAbel/PyAbel#36]
Since there is an increasing number of implementations that will be merged into PyAbel in the future (including issues #27 , #35 , #24 , #30 , #23 ), it would be good to agree on some consistent naming scheme for different functions. This issue aims to discuss how we will handle this in PyAbel >= 0.7, and is a continuation of the discussion in issue #14 . 

Here is a first working draft, closely based on the way different minimization solvers are handled in [`scipy.optimize`](https://docs.scipy.org/doc/scipy-0.16.0/reference/optimize.html). So we could, for instance, define general wrappers for the forward and inverse abel functions as `abel.fabel` and `abel.iabel`,  with the following example:

          import abel
          abel.iabel(data, method='BASEX', options={})

where `data` is a centered array, `method` is the implementation that should be used, and `options` a dictionary with the implementation specific options. 

The specific naming for different implementations, located under `abel/<implementation>.py`  could be then,
 -  `abel.fabel_<implemenation>`  :  forward transform (when defined)
 -  `abel.iabel_<implemenation>` :  inverse implementation (when defined)
 -  `abel._bs_<implementation>` :  function that generates  the basis sets (if necessary)
 -  `abel.bs_<implementation>_cached` : function that loads the basis sets from disk, and generates them if they are not found (if necessary).

The centering function and the velocity  maps are imported as presently from under `abel.tools`.

Below is the list of present and planned implementations, with a list of features, including,
  - **Name** : the name of the method
  - **Version**: version of PyAbel when it is planned to be added
  - **Symmetry**: the symmetry of the reconstruction,
      - `None`: the parts for the image for `r>0` and `r<0` (and for every `z` value) are reconstructed separately, assuming that they represent and object with a cylindrical symmetry
      -  `r`:   The reconstruction verifies `f(r,z) = f(-r, z)`
      - `r`, `z`: The reconstruction verifies `f(r,z) = f(-r, z)` and `f(r,-z) = f(r, z)`  (polar symmetry?) 
  - **Basis sets:** implementation uses pre calculated basis sets
  - **`dr = cst.`:**  implementation requires uniform sampling of the image along the `r` axis. 

and naming conventions,
 
   - **`method`**: the value of the argument given to the wrapper `abel.abel(... method=method)`
   - **Files** : files under `abel/` where the code is located
   - **Core functions**: low level core functions that perform the transform of the centered signal
   - **Basis set functions**: low level core functions that generate basis sets (if that is necessary)
   - **Wrappers**: wrappers that perform centering, (optionally) basis set generation, and the transform
 
##### Features
| Name                      | Version    | Symmetry | Basis sets | `dr = cst.` | Comments |
|:-------------------------:|:----------:|:--------:|:----------:|:-----------:|:--------:|
| Fourier Hankel            | `>=v0.7`   | `None`      |            |   ✔         |          |
| Direct integration        | `v0.7`     | `None`      |            |             |          |

##### Naming conventions

| Name                      | `method`   | Files      | Core functions  | Basis set functions    | Wrappers |
|:-------------------------:|:----------:|:----------:|:---------------:|:-----------:|:--------:|
| Fourier Hankel            | `FH`       | `fh.py`    | `fabel_fh`      |    None         |  None    |
| Direct integration        | `direct`   | `direct.py`| `fabel_direct`  |    None         |  None    |

##### Features

| Name                      | Version    | Symmetry | Basis sets | `dr = cst.` | Comments |
|:-------------------------:|:----------:|:--------:|:----------:|:-----------:|:--------:|
| BASEX                     | `v0.6`     | `r`, `z` | ✔          |   ✔         |          |
| BASEX                     | `v0.7`     | `r`      | ✔          |   ✔         |          |
| Fourier Hankel            | `>=v0.7`   | `None`?  |            |   ✔         |          |
| Direct integration        | `v0.7`     | `None`   |            |             |          |
| Hansen & Law              | `v0.7`     | `r`, `z` |            |   ✔         |          |
| Polar Onion Peeling (POP) | `v0.8`     | `r`, `z` | ✔          |   ✔         |          |
| Onion Peeling (OP)        | `>=v0.7`   | `r`      |            |   ✔         |          |

##### Naming conventions

| Name                      | `method`   | Files      | Core functions  | Basis set functions    | Comments |
|:-------------------------:|:----------:|:----------:|:---------------:|:-----------:|:--------:|
| BASEX                     | `BASEX`    | `basex.py` | `iabel_basex(..., vertical_symmetry=True)` |   `_bs_basex`, `bs_basex_cached`,         |     ???     |
| BASEX without up/down sym| `BASEX_asym`    | `basex.py` | `iabel_basex(..., vertical_symmetry=False)`|   `_bs_basex_asim`, `bs_basex_asim_cached`     |    ???      |
| Fourier Hankel            | `FH`       | `fh.py`    | `iabel_fh`      |   None          |  None    |
| Direct integration        | `direct`   | `direct.py`| `iabel_direct`  |   None          |  None    |
| Hansen & Law              | `HansenLaw`| `hansenlaw.py`| `iabel_hansenlaw`|   None      |  None    |
| Polar Onion Peeling (POP) | `POP`      | `pop.py`      | `iabel_pop`     |   `_bs_pop`, `bs_pop_cached`   |          |
| Onion Peeling (OP)        | `OP`       | `op.py`       | `iabel_op`      |   None       |          |

@DanHickstein This also addresses your questions regarding function names from PR #28 and #22, I didn't respond to at the time. 

So  this is a first draft, mostly to have some basis for this discussion. Let me know what you think about it. 

In particular, this draft has following issues:
   1. **BASEX**: I'm struggling a bit for the `method` names (and short functions names) for BASEX without up/down symmetry (i.e. pyroBASEX). 
   2. `import abel` and `from abel import abel` would result in the same name, which is confusing
   2. I'm not sure what would be the best way of implementing wrappers that do centering/basis set generation and transform in one line; as proposed by @DanHickstein . I don't think it would be practical to implement it for every single transform. Maybe handle it at the level of a general wrapper such as for instance `abel.center_iabel_vmi(..., method='BASEX')`, so it is not confused with the function that only does the Abel transform? We can also keep the  `BASEX` function the way it is for backward compatibility, I'm just wondering what would be the best way of handling it in the future...  

A few additional notes:
   - It is debatable whether `from abel import abel_basex` is better then `from abel.basex import abel_basex`. On the other hand, I'm a bit against `from abel.basex import abel` (or `import transform`), as functions should have a unique name within the module (as it is for instance the case within scipy). 
   - `basis_sets_` something, makes really long function names, so one way of doing it could be to abbreviate it to `bs` as I proposed here, but maybe some intermediate solution would be doable.

For other naming proposition, I guess the only other would be the Python naming conventions for [modules](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) and [function](https://www.python.org/dev/peps/pep-0008/#function-names).
  
Please let me know your thoughts on this. You should also be able to edit this comment (and in particular the tables above) at any point of the discussion so we can converge to a naming system that everybody agrees with.

**Comment by DhrubajyotiDas** [comment]
This is great work @rth. Given how aggressive we are planning to be in the future when it comes to incorporating new implementations, having discussions on the structure early on is very productive. Thanks for the writeup!

Regarding asymmetric-BASEX: given how similar the mathematics is to regular-BASEX, I support your proposal to name the pyroBASEX versions of the BASEX functions in a similar fashion, with an `_asym` or `_no_sym` suffix.

**Comment by DanHickstein** [comment]
Thanks Roman! It's a great idea to have a big-picture view of the naming conventions. I have a few thoughts:

1. I like the idea of the wrapper functions. I think that you are basically saying that inverse abel methods should not concern themselves with the image centering, and we should rely on the user to apply the ``abel.tools.center_image()`` function before applying an inverse abel transform. This would make things easier for us, and this is only two lines for the user to do a basic inverse-transform, so this is fine as far as I am concerned.

2. I believe that some of the transforms, especially those composed of broad basis functions, like POP or pBASEX, will have methods for calculating the 1D "speeds" distribution that will be unique to that transform method and won't be taken care of by the function in tools.py. Same for the anisotropy parameters. So, I think we would need to accept the fact that the abel.iabel wrapper would sometimes return more than just the 2D image.

3. In the case that the transform just calculates the 2D image and we are extracting the speeds distribution from the simple angular integration (the case for BASEX), then I suppose that I am okay with just letting the user calculate this on their own with ``abel.tools.calc_speeds``. So, a "three line" transform would be acceptable if we think that this makes everything easier.

4. We should take care to let the wrapper function pass sensible default values to all of the different transform methods so that users will not need to pass too many arguments if they are just looking for a basic transform. 

5. To avoid the ``from abel import abel`` problem, we could just name the forward abel wrapper ``fabel`` or ``forward_abel``. I suspect that these will be much less used than the inverse methods, so a slightly clunkier name is fine if it avoids the name overlap. 

Otherwise, I think that this looks really good!

**Comment by rth** [comment]
Thank you all for the feedback!

@DanHickstein In order,

1. ..

2. Hmm, I see your point. I'm not so familiar myself with those applications of the inverse Abel transform. How about the `abel`/`iabel` wrappers return an object instead of a tuple of variable length. For  instance, in the latter case if we wanted to loop thought different methods we would have to do something like,
         
         res = iabel(..., method=some_method)
         if isinstance(res, tuple) and len(res) == 2:
             recon, velocity = res
         elif isinstance(res, tuple) and len(res) ==  3:
             recon, velocity, anysotropy = res
         else:
             recon = res
while in the former case, we could just do something like
   
          res = iabel(..., method=some_method)
          recon = res.data
          if res.velocity is not None:
                 velocity  = res.velocity
          # etc.
3. I you would agree on this 3 line call for a generic `iabel` that would be great, and much easier to implement :)

4. I agree completely. 

5. Aww, yes I like `fabel`! And it is consistent with the `iabel` wrapper name. I changed my original post to reflect these changes. Thanks!

**Comment by DanHickstein** [comment]
Yup, the three line solution is fine. It makes it more clear the user what steps are being performed, and it will make it clear what type of angular integration is happening. 

I also like the idea of returning an object, where the user can get the transform with ``result.transform`` or something like this. 

This opens even more possibilities. For example, in BASEX (and I assume most other methods), it is also possible to calculate the projected image using the same coefficients matrix that calculates the slice (transform). Users might want to use this image in order to compare it with the raw data and calculate the residuals in order to get some idea of how well the transform is working. 

In addition, I can envision the various iabel transforms returning 
```
results.transform
results.projection
results.radial_intensity
results.anisotropy
```
and maybe others. So, having ``abel.iabel`` return an object (or, I guess dict) seems like the only way to go to ensure consistent behavior.

**Comment by DanHickstein** [comment]
I think that perhaps ``results.transform`` would be better described as ``results.slice``, since "transform" is ambiguous if it's a forward or backwards transform, which "projection" is certainly a result of a forward transform.

**Comment by DanHickstein** [comment]
In https://github.com/PyAbel/PyAbel/pull/54#issuecomment-167264829, @stggh suggested that we do away with the ``i/f`` prefix in instead just combine both the inverse and forward transform into one function with a boolean ``inverse=True`` to control whether the function performs the forward or inverse Abel transform. At least for the the ``direct`` and ``hansen_law`` implementations, this would allow us to use a smaller number of functions and therefore make the code easier to understand.

This is a fair point, and I would ask @rth and @DhrubajyotiDas for their opinions as well.

When we picked the ``iabel_/fabel_`` style, I think we were motivated by a desire to make it very explicit to the user if they were selecting the forward or inverse transform. I think that all users want specifically the forward or reverse transform (or both), and we should try to make it as clear as possible which transform is being employed. From our (the developers) viewpoint, the transform algorithm (BASEX versus Hansenlaw, etc.) sees like the most important thing, but the first thing that a user cares about is the direction that the transform is going. So, from this viewpoint, I really like the ``fable/iabel`` naming system. 

In general, I like the idea of reducing the number of functions, but I think that a function like
```python
def fabel_hansenlaw(IM, dr=1, **args):
    return _abel_hansenlaw_core(IM, dr=dr, inverse=False, **args)
```
is pretty straightforward to understand. (Note that I changed your text "wrapper" to "core", since a "wapper" function is, in general, a higher level function that packages a lower level one. In this case, ``fabel_hansenlaw`` is the wrapper.)

So, I think that I like our current naming system, although I realize that it's perhaps not the most streamlined when it comes to reading the code. 

Other thoughts?

_____

Looking back at the previous discussion on this page, I think that we should start to implement the high level functions ``abel.iabel`` and ``abel.fabel``, which can provide a way to provide things like quadrant averaging in a consistent way for all the transform methods. I.e., the hansen-law method would not need to have any quadrant averaging code because this would be contained in the higher level functions.

**Comment by DanHickstein** [comment]
I think that we can finally close this issue. We have decided that the over-arching function should be called `abel.transform()`, and that the direction (`'forward'/'inverse'`) will be passed with the `direction` keyword as 
```python
import abel
abel.transform(data, direction='forward')
abel.transform(data, direction='inverse')
```
We are still discussing the naming of the individual functions in Issue https://github.com/PyAbel/PyAbel/issues/96.
