### ISSUE TITLE
re-implement Python 3.10 testing on linux

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#366]
As mentioned in #364, we disabled Py3.10 testing on linux due to a weird issue with Travis CI. This is a reminder to make sure that gets re-implemented at some point. Of course, if we move away from Travis CI as discussed in #365, then this will no longer be relevant.

**Comment by MikhailRyazanov** [comment]
Now we should be able to test with any Python 3.x using GitHub Actions (#390), but 3.10 itself is already [out of full support](https://peps.python.org/pep-0619/#bugfix-releases) (since April 2023). We currently do run tests for 3.13 (the latest Python release) and 3.7 (the earliest declared as supported) in every OS, so this issue is perhaps not very relevant any more?

**Comment by DanHickstein** [comment]
Yup! Thanks for your great work getting the GitHub Actions working.
