### ISSUE TITLE
Discretization of the grid for the Abel transform

### ISSUE THREAD

**Issue by rth** [PyAbel/PyAbel#39]
While I think we all agree on the definition of the image center as discussed in issue #34 , illustrated on the figure below, 

![test](https://cloud.githubusercontent.com/assets/630936/11503290/1c7e06f4-9840-11e5-9791-76d18db76ca5.png)

the fact that the transform requires odd or even images, also has wider implications on the spatial discretization assumed by the algorithm (which I have personally never considered). For instance in 1D, the two possible discretization are illustrated on the figure below,

![abel_discretization](https://cloud.githubusercontent.com/assets/630936/11503199/90bb9a96-983f-11e5-88cc-e153f63f019b.png)
where the pixel size is `dr`. @stggh Regarding your earlier comment, both approaches are uniformly sampled, as far as I understand. 

Although, in practice, far away from the origin, I suppose it shouldn't really matter, the way the grid is discretized is probably a fundamental property of a given implementation. Therefore,  I'm not sure we can expect all implementations to support both odd and even images. For instance at present, it appears that there is the following separation,

 - **Odd images** : BASEX, BASEX_asym (originally)
 - **Even images**: HansenLaw, direct (I think), Fourier-Hankel (I think)
 
Another applications is, for instance, 2D cylindrical fluid dynamics simulation, that I project with the forward Abel transform, are also in the "Even images" case.  

In the particular case of the `direct` implementation, I'm not so inclined to redo all math to see what it should be if we change the discretization of the grid for odd images, nor do I think it would be that useful (more code => more possibilities for bugs, possible inconsistent behavior between odd and even images, and finally it shouldn't matter anyway for real data of > 1000px ).   

So the question is whether in general we should,

 a. Raise an error if e.g. an algorithm working with odd images is given an even image
 b. Hack the input/output image  as to work both with odd and even images, while actually providing the transform with the an image of the parity it supports. For that  we could use @DhrubajyotiDas proposition, i.e: 
   - *even -> odd*:  add a fake central row, as an average of the neighbor rows, then remove it after the processing
   - *odd -> even*: split the central row in 2, then take the average of the resulting 2 rows before outputting the image.
This would introduce some additional error, particularly near the origin, because of a shift by 1/2 pixel of the whole image when this hack is used, but I don't think it would be that bad, particularly as the data near the origin is noisy already in the majority of implementations. 

If we decide to go with b., it would make sens then to go with an implementation, that could be used in all the implementations and not just as a fix to the BASEX algorithm.

Let me know what you think about this.

**Comment by stggh** [comment]
Wow, amazing work you guys, overnight (oz time). Invigorating!

I was thinking about exactly this speed grid issue. Your grid diagram is excellent. The problem that I see what does tools.generate_speeds() use for as the grid, in combination with tools.reproject_image_into_polar()? Or is it not important. At the moment we force the user to associate radius (velocity) to the speed intensity distribution, when we should return (R, speed)?
I may be confused, but the 0->R grid should correspond to the **mid point** of each pixel, with the centre of the image always, 0. Hence, oddly enough, the even-image has a grid offset (case B), and the odd-image corresponds to the integer grid.  The bottom line is that the R grid should also be returned. 

@rth:
* HansenLaw can handle odd images, without the need for padding, but not, at the moment, the way I implement the algorithm. An odd or even sized length row of data (pixels) does not matter.

a. Warning error, allow the method to proceed. In general, the result is "nearly" correct, and better than nothing.

b. It may be that only basex requires odd images. The "quick fix" even->odd requires the speed distribution grid, as I identified above. odd->even may not be required for the other algorithms.

**Comment by DanHickstein** [comment]
I like the idea of only letting the transform operate on images where it produces the right output. But, as @stggh point out, it might be nice to just have a warning, since 90% of users will not care if the transform is shifted by a pixel. 

One approach would be to let the low-level functions, like ``abel.iabel_basex()`` demand images that meet the requirements of the method (odd, as far as our current basex implementation goes) and throw an error if given the wrong shape image. However, the user-friendly wrapper function (``abel.iabel(im,method="basex")``) could accept inputs of the wrong shape. ``abel.iabel`` would then modify the image to be the correct shape and print a warning that the wrong image shape was supplied and that the transform may be slightly shifted.

The question of what the heck the ``reproject_into_polar()`` function is actually doing is anyone's guess, since I just borrowed that code from Stack Overflow. Confirming that ``reproject_into_polar`` is doing the appropriate for all image geometries should be on our to-do list.

**Comment by stggh** [comment]
```reproject_into_polar()``` does not appear to handle even pixel sized images, due to the use of (integer,integer) coordinate image centre, and the associated ```np.meshgrid()```. I am investigating the path forward to evaluate the speed distribution for even images.

**Comment by stggh** [comment]
Supplying the real origin, for even images, ```calculate_speeds(recon,(N2-0.5,N2-0.5))```, produces agreement.
![hl basex](https://cloud.githubusercontent.com/assets/10932229/11556562/ab45aa74-99fb-11e5-9ced-60f0aac190c8.png)

All good now. You code for basex odd images was correct all along.

**Comment by stggh** [comment]
I have revisited ```abel.tools.reproject_image_onto_polar()```

   0. The (old) comments describe a png image, which has (0,0) is bottom left, not the case for numpy arrays.  

   1. The default origin is (ny//2, nx//2), and hence the method does not correctly handle an odd-size image.
      
       Adding +ny%2, +nx%2  to the origin coordinate corrects this issue.

   2. The polar grid is defined as r= [0:r.max()], and &theta; = [&theta;.min():&theta;.max()], with respective step sizes determined by ```nr=r.max()```, and ```nt=ny//2```. These coordinates are then used to interpolate the original image. The choice for ```nr``` and ```nt``` is arbitrary, there may be good reason to use larger values, a smaller grid.

       passing and additional parameter ```polar_grid=None``` to allow specifying ```nr, nt``` as a tuple, limits aliasing. This parameter is now available to ```calculate_speeds()```.


   3.  I have also added the parameter,  ```Jacobian=False```, to include sin&theta; in the summation over angle, so the integration over angle is &int; P(r, &theta;) sin&theta; d&theta;

Here is an example plot. The left side illustrates the effect of sin&theta;, which in the case of negative anisotropy parameter (&beta;) conveniently suppresses the low &theta; (and near &pi;) intensities which have inverse Abel transform noise. The right side shows the effect of reducing the polar grid size, the transition peaks are less truncated.

![jacobian](https://cloud.githubusercontent.com/assets/10932229/12077166/c53b9c1e-b228-11e5-9855-9026356fd8c7.png)

**Comment by stggh** [comment]
Given the additional parameters for ```abel.tools.calculate_speeds(IM,  origin=None, Jacobian=False, polar_grid_sizes=None)``` I think that there is a case for removing the ```calc_speeds``` option, and parameters from ```iabel_<method>()```, since, in principle this function should just return inverse Abel transformed image. Otherwise, the parameter space, and definitions, becomes messy. Thoughts?

**Comment by DanHickstein** [comment]
Thanks for taking a closer look at this @stggh! 

1) I agree that the "move the origin back to the lower left corner" comment is inaccurate/misleading. It's from the stackoverflow post, and it seems like Joe Kington (the guy who made that post) considers the [0,0] index to be the lower left corner. I think that PNG uses [0,0] as the *upper* left corner, and though a numpy array doesn't necessarily have a spatial orientation, ``plt.imshow`` defaults to putting [0,0] in the upper left as well. So, you are correct in both cases I believe.

2) Great! I'm glad that the fix is easy and that it can now work for odd-sized images.

4) (Answering out of order) I'm slightly confused about how the Jacobian plays out. I think that once we have our data in r and theta coordinates, then the Jacobian for the angular integration is ``r*sin(theta)``, since we are assuming a 3D cylindrically symmetric object. Basically, when we rotate the slice we get more volume for pixels that are further from the axis of cylindrical symmetry (r*sin(theta)). 

However, when we transform from cartesian to polar coordinates, I think that there is also a Jacobian of ``r``. Basically, at low ``r``, we are spreading the intensity into numerous ``theta`` bins, so we need to compensate by multiplying these by ``r``. So, the total Jacobian would be ``r**2 * sin(theta)``. Am I thinking about this correctly? Note that the Jacobian of ``r`` should be implemented by the ``reproject_image_into_polar()`` function, since it's a result of the coordinate transform. The ``r*sin(theta)`` factor should be applied by the ``calc_speeds`` (it's called something different now) function.

Oh, and there are probably some ``dr`` and ``dtheta`` terms that I forgot about. ``reproject_image_into_polar()`` should probably also multiply by dr and dtheta.

3) You make a good observation that the choice of the (r,theta) grid is arbitrary and can have an effect on the outcome. Currently, we are picking an r-grid that should match the pixel spacing of the image, so this seems roughly sensible. I can't imaging that using a grid that is too much smaller than this would help much, but perhaps using twice the number of r-points would help. 

The number of points in theta is being set to ``nt = ny//2``, which seems quite arbitrary indeed, and will certainly be too small in some situations. For example, if I think about a square image with pixel dimensions ``(N,N)``, then, at the edge of the image, one pixel represents a theta step of ``arctan(1/N)``, which in the small angle approximation is 1/N. To adequately sample this step in theta, we would need 2*pi*N values of theta. So, over 6 times what we are currently using. 

I think that I sort-of realized this a few years ago, but elected to use fewer theta bins since it considerably sped up the reprojection into polar coordinates. When I switch ``nt=ny//2`` to ``nt=ny*2*np.pi``, this causes the speeds calculation to slow from 0.18 seconds to 1.08 seconds for a 2048x2048 image. So, it scales approximately linearly with the number of theta steps.

Also, I should probably not have set the theta step using ``ny``, since this won't provide consistent behavior for rectangular image. Probably ``np.max((nx,n)y)`` should be used.

I am not quite sure how to handle this. Providing a grid size that is adequately small for all situations seems to cause quite a performance hit, but it seems like the right thing to do. Perhaps we can allow the ``calc_speeds`` function to take ``nr`` and ``ntheta`` as arguments, and users can either specify the actual value or leave them to their default values of ``ntheta='fine'`` to have them automatically assigned to ``nt=np.max((nx,ny)) * 2 * np.pi``, and perhaps also a ``'coarse'`` setting that uses something more like ``nt=np.max((nx,ny)) * np.pi//4``. 

One other option would be to use a triangular array for the polar image, like the one described in the [Polar Onion Peeling paper](https://community.dur.ac.uk/j.r.r.verlet/PUBLISHED/2009_2/RSI_80_053104.pdf) and implemented in this [matlab code](http://www.mathworks.com/matlabcentral/fileexchange/41064-polar-onion-peeling). Here they change the theta size in order to provide polar bins that more-or-less match the cartesian grid:

![image](https://cloud.githubusercontent.com/assets/1107796/12077400/fccd74d4-b19e-11e5-9667-461389adf595.png)


Regarding your last question, the plan is to move the speeds calculation out of the ``iabel_<method>()`` functions, since this calculation is the same for all of the transform methods so far. So yes, the ``iabel_<method>`` functions provide only the 2D transform.

**Comment by stggh** [comment]
@DanHickstein you have immense clarity of thought! 

 4) You are right, the Jacobian should be ```r**2 sin(theta)``` and include the ```dr, dtheta``` terms.  I imagined that the missing ```x r``` factor was at the conversion of speed (```r```) into energy transformation (```r**2```).  I need to think this through further. The O<sup>-</sup> PES is not super sensitive to ```x r``` factors, but, along with O<sub>2</sub><sup>-</sup> PES, and other species, provide a good check. 
e.g. the original ```basex.exe``` speed calculation needed a ```1/r``` intensity factor, due to the way the Abel transform is defined (in the associated paper).

3) ```reproject_image_into_polar``` provides the opportunity to reshape the projrcted image. I am not sure this flexibility should be closed off. I like your solution of ```nr, nt ='fine'``` and ```'coarse'``` defaults, since the user is unlikely to know what to choose. I am happy to go with that.

The triangular array is interesting, but how is it possible to follow the r-axis? I will take a look at the method.

x) I an happy to extract ```calc_speeds``` from ```hansenlaw```

**Comment by DanHickstein** [comment]
4) Oh, I didn't see your check of the ratios using the O- data. That's really cool! Does it still work when we add the extra r factor?

3) Yes, we should maintain the ability to reshape the image with the ``reproject_image_into_polar()`` function. ``nt`` and ``nr`` can be any integer, or the user can supply the ``fine/course`` strings to have the number automatically generated from the image dimensions. Can you check with your data to make sure that having ``fine`` correspond to 

```
nt = np.max((nx,ny)) * 2 * np.pi
nr = np.max(R)
# Where R is a list of all of the radial coordinates in the image. 
```

is sufficient? 

I also wonder if we should provide an option to crop the output array to the largest r-value that contains data at all angles. I.e., even in a square image, there are regions at the corners that should probably be ignored. Since we would basically be cropping a circle from the original image, this presents the hilarious opportunity to include a ``crop_circle=True/False`` flag. 

The triangular array looks very similar to our current matrix of theta versus r, except that the theta values are different for each row of r. Here is a screenshot of the matlab code showing the transformation. Original image is no the left, triangular matrix is on the right. The y-axis is the r value, and the x-axis 
![image](https://cloud.githubusercontent.com/assets/1107796/12079875/301689a4-b206-11e5-8fb0-3f0d5d8a0e3b.png)

The only advantage of the triangular array approach would be that it wouldn't oversample (in theta) values at low r. But, as long as we incorporate the jacobian of ``r``, we correct for this anyways and it should not be a problem. Our current rectangular array approach allows us to easily see any r value as a function of theta without doing any extra work. This is probably a large enough advantage that we should just stick with our current approach.

**Comment by stggh** [comment]
4) Yes, the extra r scaling is required, the *correct* Jacobian is <math>r<sup>2</sup>sin&theta;</math>

(rough) Gaussian function fits to the <math><sup>3</sup>P<sub>J</sub> &larr; <sup>2</sup>P<sub>3/2</sub></math> transitions. Table of amplitudes (FWHM ~ equal), not sure about the validity of the fit error estimates `(#)`:

  r sin&theta;  |    r<sup>2</sup> sin&theta;  | theory
------------------ | ------------------------------------ | ---------
  0.104(4)      |       0.078(4)    | 0.08
  0.407(4)      |       0.340(4)    | 0.36
  1.012(4)      |      1.012(4)     | 1

3)  nr, nt limits: 
    (i) ```nr = r.max()```     to remap the while image
         ```nr = np.min((nx,ny))```  for the speed distribution. Note the ```min()```

   (ii) ```nt = np.max((nx,ny)) * 2 * np.pi```   'fine'    and ```*np.pi/4``` 'coarse'

   In this case use of ```min``` or ```max``` make little difference.

   I will check these grids sizes on the O<math><sup>-</sup></math> PES
    
For the ```nr, nt``` parameters I am concerned about mixing types, string/integers, without creating a code mess and/or user confusion. The requirements of a polar_image projection (a pixel shape, with definite nr, nt) are different to the speed distribution (a grid).  For speed I would prefer a grid with a nice spacing, ```dr =1```, or ```dr = 0.1```, a value which is not easily deduced in specifying the parameter ```nr```.
For ```nt``` the ```2``` or ```1/4``` factors become somewhat irrelevant for large ```nx, ny```. I think these aspects require some more thought/@DanHickstein innovation/arbitration.

 Triangular array:  I agree, we should stick with the current approach. For our current inversion methods the noise accumulates near the image center(-line), and so accurate intensity interpolation near the image center is less important.  For completeness, at some stage the method should be included in the PyAbel arsenal of tools.

**Comment by DanHickstein** [comment]
Okay, so the r**2 sin(theta) looks good. Awesome!

For the ``nr, nt`` situation, I don't see too much problem with letting the user specify a string or a value. I think that it's pretty common in numpy/scipy to allow a variable to be, for example, either a single number or an array of numbers. I think that I've also seen situations where a argument can either be ``'auto'`` or the values can be specified. As long as we document it well, it should not be too confusing. I think that it's important to provide some guidance to the user about what values are appropriate (as we are doing with the ``coarse/fine`` presets).

It also seems fine that the ``reproject_image_into_polar()`` function accepts arguments in terms of ``nt`` and ``nr``, while the function calculating the speeds accepts ``dr`` and ``dtheta``. The function calculating the speeds can simply calculate the appropriate numbers to pass to the ``reproject_image_into_polar()`` function. The function returning the speeds calculation could also return an array of the r-values, just to make it clear to the user and to make it easier to consistently plot the data even as the user adjusts the ``dr`` parameter. 

You mention that the exact ``nt`` value becomes irrelevant as ``nx,ny`` become large. This is true if your features remain broad. In principal, any image size could contain a feature the size of one pixel near the edge. The exact value of ``nt`` would determine if this feature is resolved or not. So, it's a question of if we want to default values to deal with a "worst case" scenario at the expense of making the calculation take longer. Actually, I think that it would be fine for the default values of the ``calc_speeds`` function to be different than those for the ``reproject_image_into_polar()`` function. ``reproject_image_into_polar()`` should default to a fine theta step to be able to resolve all of the features, while ``calc_speeds`` could use a larger theta step on the assumption that those performing the full integration may be less sensitive to fine angular features. 

Good to get this stuff worked out before our overly coarse theta grid fools someone in the future!

**Comment by stggh** [comment]
For my own photoelectron measurements I(&theta;) may vary no faster than <math>(3 cos<sup>2</sup>&theta; - 1)/2</math>, so angular resolution is not so much of a problem cf the radial coordinate. In this case ```nt``` need only to be large enough to sample the <math>cos<sup>2</sup></math> function. Hmm, I now see no advantage in increasing ```nt``` beyond the default of ```nx or ny```!
In fact the (fat) chunky pixels(1) limit how large ```nt, nr``` may usefully be (I think you mentioned this earlier).  Possibly, ```nr <= 2*r.max()``` (```dr = 0.5```).  Hmm, I was wrong about the flexibility of polar reshaping, as the interpolation is limited by the cartesian original image size. 

I now believe that ```nt = ny//2``` may be fine. ```nr = nx```,    2x larger may be enough. No need for parameters.

(1) I was lead astray by my own experimental method in which an image of arbitrary size is generated from centroided sub-pixel electron positions. Larger pixel images provide better resolution (but less signal).

**Comment by stggh** [comment]
Sort of back to square 1 (sorry!):

The ```reproject...()``` method has:
```r_i = linspace(r.min(), r.max(), nr)``` and ```theta_i = linspace(theta.min(), theta.max(), nt)``` 
with  ```nr = r.max()``` and ```nt = ny//2```.  Note, ```dr``` is more than 1, because ```linspace``` includes the upper limit (and so ```calculate_speeds()``` must return the ```r``` coordinate values).

The orginal stackoverflow (Kington) code uses ```nr=nx```, ```nt=ny```. i.e. a grid size twice as large.
The Kington values for the polar image are probably optimal, and return the same shape image.

With the speed calculation ```r``` should only include the largest whole circle i.e. ```nr = np.min((nx,ny))//2```.  @DanHickstein suggestion of a 'coarse' grid ```dr=1``` or 'fine' grid ```dr=0.5```, parameter option, is adequate. i.e. ```linspace(0, nr//2+nr%2-1, 2*(nr//2+nr%2)-1)```.

For theta, ```nt ~ 360```, equivalent to a 1 degree interval is probably more than enough. So, ```nt = ny//2``` *should* be more than adequate.  If we are looking to reduce execution time, then 360 might be a better choice. I will investigate how the speed distribution changes with the mgnitude of ```nt```.

**Comment by stggh** [comment]
I modified ```tools.calculate_speeds(), reproject...()``` to pass ```dr``` and ```dt``` (in degrees), and then evaluate ```nr, nt```.

The figure is the O- PES shown above in the radial region of the strongest peak.

![o-speed-vs-drdt](https://cloud.githubusercontent.com/assets/10932229/12089279/4304dcb4-b337-11e5-8349-d2ceab0771ca.png)

The left figure, varies ```dr=1, 0.5, 0.1``` and the resultant ```nt``` is shown. It is seen there is an improvement in reducing ```dr``` to 0.5, and little in going further. i.e. ```nr = ny = 1024``` appears sufficient.

The right figure, varies ```dt``` in degrees (for ```dr=0.1```). Here, quite small large ```dt``` (small ```nt```) are ok. The default is ```nt = nx//2 = 512``` is fine.

I think the defaults should be ```nr = np.min((nx,ny))``` (2x old value) and ```nt = nr//2``` (same), and allow ```dr=None, dt=None``` to be specified as the user requires. ```calculate_speeds()``` must also return the `r` co-ordinate grid, and IMO, might as well return `theta`.

**Comment by DanHickstein** [comment]
Thanks for doing this analysis! 

Having ``dr=0.5`` makes some degree of sense. Maybe there is some analogy to be made to Nyquist sampling...

And good catch with the linspace. I suppose we should be using ``np.max(r) - 1`` as the upper limit. 

The sensitivity to r and the insensitivity to theta makes sense considering that your images have narrow radial features and broad spectral features. For photoelectron images, this is generally the case and we can see a substantial performance gain by using a coarse angular step. 

The ``polar_integrate()`` function (this is what we decided to call the combined ``calc_speeds()`` and anisotropy calc function, right?) can use default values that are optimized for speed and the broader angular features seen in photoelecton/ion spectra. 

In my view, the ``reproject_image_into_polar`` function may see broader usage, since it is the only python function that I know about that does this, and reprojecting an image into polar coordinates seems like a fairly common task for a scientist. So, for this function, I'd like to at least have the option for the user to specify the ``fine`` grid, which would be sufficient to sample all features, even a single pixel at maximum ``r``.

To me, it doesn't make much difference if we specify ``nr,nt`` or ``dr,dt``. Actually, it's a weird situation, because ``dr`` is the same for all image sizes, while the appropriate ``nt`` or ``dt`` depends on the image dimensions.

In any case, we should add an additional functionality to ``reproject_image_into_polar()`` to allow the user to specify the maximum r value. ``rmax='circle'`` would set the maximum r-value returned to be np.min(nx,ny). ``rmax='all'`` would set the maximum r-value to ``np.max(r)`` as is done now. Or, the user can specify the actual number. Currently, we are calculating the projection out to the maximum r-value and then cropping it in the ``calc_speeds()`` function, which is inefficient.

**Comment by stggh** [comment]
>The polar_integrate() function (this is what we decided to call the combined calc_speeds() and anisotropy calc function, right?) 

I missed that discussion, but it makes sense to have just one function.

`reproject_image_into_polar(data, origin=None, dr=None, dt=None)`:  My (rough) code selects `rmax` based on whether `dr` is specified. I am not sure that it is necessary to add another parameter?

**Comment by DanHickstein** [comment]
I think that rmax and dr should be specified independently. For example, some users may want ``rmax=np.min(nx//2,ny//2)``, (i.e., the largest circle that can fit into the rectangular image), while other users may want ``rmax=np.max(r)``, (i.e., the largest r-value, which lies in the corner of image).

**Comment by stggh** [comment]
For the radial profile `rmax=np.max(r)` makes no sense. The data beyond `nr=np.min((nx,ny))` has no value. Each radial profile moving (in angle) away from the image corner(s) is further truncated. The speed  distribution beyond `nr` is a sum mostly of zeros, with a little piece of intensity.

However, perhaps, I am missing the end use. I am happy to go with your call.

**Comment by DanHickstein** [comment]
Now that I think about it, maybe for simplicity it's best to keep the calc-speeds and anisotropy calculations separate, even if it means that we duplicate the projection. It's possible that we want to use different defaults for the ``nr`` and ``nt`` values for the two functions anyway. 

You're correct that it doesn't make much sense for the ``calc_speds()`` function to use r-values that are beyond the largest circle that can fit in the image (``np.min((nx,ny))``). However, for the ``reproject_image_into_polar()``, I can imaging some situations where the user has real data near the corner of their image and they wish to see that data on their polar plot, even though not all of the newly generated (r,theta) grid will have defined values. In any case, I agree with you that ``rmax='circle'`` should be the new default behavior for ``reproject_iamge_into_polar()``. Users who want the other behavior can specify ``rmax='corner'`` or input their own value. 

I think that it's important to also let users specify any arbitrary ``rmax`` to ``reproject_image_into_polar()``. For example, if they are starting with several images of different sizes, but they wish to plot them all onto the same size r,theta grid, then the ability to specify ``rmax``, ``nr``, and ``nt`` allows this.

**Comment by stggh** [comment]
Phew! I looked at combining the two `calculate_` functions, and it was not straightforward.

Agreed. `dr, dt, rmax='circle'/'corner'` parameters for `reproject_image_into_polar()`. 

`calculate_speeds()` can set `rmax='circle'` for the call to `reproject_image_into_polar()`.
