### ISSUE TITLE
abel.tools.calculate_speed v0.7 returns shape n/2

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#44]
speed array appears to be 1/2 size

```
In [1]: from hansenlaw import *
In [2]: im = np.loadtxt("O2-ANU1024.txt.bz2")

In [3]: recon, speeds = iabel_hansenlaw (im,quad=(True,True,True,True),calc_speeds=True,verbose=True)
HL: Calculating inverse Abel transform: image size 1024x1024
HL: Co-adding quadrants
HL: Calculating inverse Abel transform ... 
3.91 seconds
Generating speed distribution ...
0.47 seconds

In [4]: speeds.shape
Out[4]: (256,)
In [6]: recon.shape
Out[6]: (1024, 1024)
```

I have updated hansenlaw.py in my fork, reducing the code size, and it "should" work for odd-size images (not yet tested). [Edit: I have realised that the recombining the inverted quadrants is wrong. Needs @rth put_image_quadrants.]

Q: Are my forked updates still transferred to the master in the same way i.e. a pull request. 
Q: Do I pull now or later?

Also, I cannot track down the location, but "reorient" is fine by me, to reduce confusion, for tools.get_image_quadrants()

**Comment by rth** [comment]
Yeah, we should make sure that every function passes some basic unit tests so code reorganization does not introduce new bugs, particularly now that there are multiple simultaneous contributors.  At least to check that a function "A" , should take such arguments and returns such output: that would already allow to detect typos and syntax errors at the test phase. 

@stggh Q1. Yes, after the PR is merged, you have to open a new PR to add new commits to the PyAbel remote master. 

Q2. Not sure if I understood your question. If it is about syncing your fork with the main PyAbel repo, my approach is to rebase regularly my forks on the remote master, as to be in sync with the latest updates there. If rebase works for you you could do that. Otherwise, merging master into your fork regularly (you can do a PR on your fork on github I think) as @DanHickstein is doing achieves the same effect.
Or do you mean when should you do this PR? Then, it's up to you. 

If you need to change stuff in `put_image_quadrants` go for it, you would just need to adapt `is_symmetric` accordingly, otherwise unit tests will fail.  `reorient` argument of `get_image_quadrants`  is in `tools.py` Line 34.

**Comment by DanHickstein** [comment]
Whoops, I broke calc_speeds. My bad. Fix is here:https://github.com/PyAbel/PyAbel/pull/45

A test would be good to save me from myself! :)

I am a Git/GitHub rookie. I mostly use the GUI (on OS X). There is a button "Update from PyAbel/master" that let's me keep my repo up to date with the master.

Looking forward to the Hansen–Law updates. You can PR now I think.

**Comment by DanHickstein** [comment]
I'm going to close this one, since the issue with the calc_speeds is resolved. If there is a problem with the quadrants, we can open a separate issue with more details.
