### ISSUE TITLE
Gaussian function definition

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#59]
Not really a PyAbel issue. 

I just wonder why the PyAbel Gaussian function is defined as:

 <math> e<sup>-r<sup>2</sup>/&sigma;<sup>2</sup></sup></math>  ?

instead of the correctly normalized function,

<math>e<sup>-r<sup>2</sup>/&sigma;<sup>2</sup></sup>&frasl;&sigma;&Sqrt;&pi;</math>

The normalized Gaussian does not change area (or physical number of particles) with the width of the distribution. The forward Abel transform is then, as given by the top formula.

I realise that this issue only concerns the placement of the factor <math>&sigma;&Sqrt;&pi;</math>, but as a physicist, it seems wrong to me that the width of the distribution should change the total intensity (total number of particles) in the image.

**Comment by DanHickstein** [comment]
I think that we just used the result from [Wolfram Mathworld](http://mathworld.wolfram.com/AbelTransform.html), which has the "sigma root-pi" as a multiplier to the projected image instead of putting it on the original image. I'm not sure why they chose that convention. It's kinda nice to have the maximum of the Gaussian at one regardless of the width. But I see your point about having the area be the same. 

It shouldn't make any difference for the comparisons, right?

**Comment by stggh** [comment]
Oh, ok. The comparisons are unaffected by the choice.

**Comment by rth** [comment]
Yeah, we took the formula from Wolfram, and it's indeed nice to have a maximum at 1.

 In particular for tests we can do either a relative error or an absolute one. The former is not sensitive to normalization, but it can be huge for near zero function with noise in the reconstruction (e.g. outward parts of a Gaussian) and in this case an absolute error is a more reliable. In this case, the mean absolute error is  more intuitive IMO when maximum of the function order of 1. Besides other Polynomial functions that we intend to implement in issue #19 , are not normalized either. So I would just keep this as it is.
