### ISSUE TITLE
anisotropy beta parameter

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#60]
I have written some rough code to evaluate the anisotropy parameter &beta;  ```tools.anisotropy()```, in my fork. Example, ```examples/example_anisotropy()```

![example_anisotropy](https://cloud.githubusercontent.com/assets/10932229/12009554/809b71d6-acd0-11e5-8bdf-e006b0db20f8.png)

Notes/issues:
(1) Code is rough, needs further testing (by me), exception checks, unit tests.
(2) Uses ```scipy.optmize.curve_fit()```.  Currently ```center_image_by_slice()``` uses ```scipy.optimize.minimize()``` - I should make them consistent.
(3) ```tools.reproject_image_into_polar()``` returns polar angle reference to the horizontal direction (? I think). Our &theta; should be with respect to the vertical direction. I am not sure whether the correction should be applied within the ```reproject...``` function?
(3) Both ```calculate_speeds()``` and now ```anisotropy()``` reproject the image coordinates. This may be wasteful, when only one evaluation is required.

**Comment by DanHickstein** [comment]
@stgg, great work! The anisotropy calculation is one of fundamental tools for many VMI spectroscopy labs, and it's a central feature of the BASEX program, so I think that many users will be looking for it. 

It would be helpful to see a definition of the anisotropy parameters, since I have never made use of them. But I am on vacation and don't have my books in front of me, and I can't find a solid definition in a paper. Do you have a textbook that has a good definition of the anisotropy parameters that you can take a photo of and post here?

What you are calculating is Beta_2, right? I know that people often like to look at higher order beta parameters, typically even ones. But in some cases odd beta parameters may be useful as well. We should probably have an option to include higher order terms.

Regarding #2: The use of ``scipy.optimize.curve_fit()`` has me a little bit worried. I'll bet that a nonlinear fit is the best way to extract beta from a nice dataset (like the beautiful ones that you collect). But nonlinear fits do not always converge, and they are very dependent on the starting conditions, often finding false minima. It seems like if we are just extracting one number from a curve, there should be a simpler way. ``scipy.optimize.minimize()`` at least lets you set the bounds on the anisotropy parameter. It seems like this should be beneficial. We should also return an estimate of the error of the anisotropy parameter. 

Regarding #3: I think that you are correct that we should set theta=0 to be in the vertical direction. I'm not sure of the easiest way do do this. Probably we can change ``theta = np.arctan2(y, x)`` to ``theta = np.arctan2(x,y)`` in ``cart2polar`` in ``tools.py`` (and swap the sin and cos in ``polar2cart``). Alternatively, we can switch things around in the ``reproject_image_into_polar()`` function, but it seems best to change our fundamental definitions of where theta=0 is. 

Regarding #4: Is the reprojection into polar coords the most expensive part of the anisotropy calculation? If so, I think that you are correct that it's silly to potentially calculate it twice. What about renaming your function something like "polar_integrate" and having it return an object with properties ``results.radial_intensity``  (aka, "speeds"), ``results.radial_intensity_std_dev`` (just to provide some error estimate for the first), ``results.anisotropy``, and ``results.anisotropy_error``. Perhaps provide a boolean argument ``anisotropy=False`` to allow users to toggle the anisotropy part of the calculation on and off. 

Eventually we can delete the current ``calc_speeds`` and replace with this new ``polar_integrate``. 

(Actually, now that I look at your function, I see that it returns a lot of other things as well. Can you explain a little more what these are?)

Currently, your code provides an option to specify the ``theta`` range used (which I think makes sense), and also the ``r`` range. To me, it seems like the calculation can just be done for all ``r`` values and the user can just as easily sort out later which values are meaningful to them. Is there a reason that the r-range must be specified at this stage?

Anyway, it's great to see a first draft working!

**Comment by stggh** [comment]
@DanHickstein thanks for your, as usual, very comprehensive code review, and for taking time from your vacation. I am also on summer vacation, and hope to head to the beach tomorrow (a not so trivial trip from an inland city). 
Just a few quick responses to some of your comments:

1. Anisotropy parameter definition
     The commonly cited reference in photoelectron spectroscopy is http://dx.doi.org/10.1063/1.1668742
![jcp48-942-cooperzare](https://cloud.githubusercontent.com/assets/10932229/12011947/3e474bee-ad38-11e5-8d19-4403265b1492.png)

Experiment measures intensity vs angle providing &beta; via Eq.(1). Quantum mechanics calculates &beta; via Eq. (2). Eq. (1) is for linearly polarized light, illuminating a non-polarized target. As you note, there are higher order anisotropy parameters, but they are not generally of importance for photoelectron measurements. It is difficult enough to determine accurate values for &beta;.

My favourite theoretical derivation is given in Chapter 2 of the thesis by Sara Thorin
"Design and construction of a velocity map imaging spectrometer" (2004) Lund University
http://www.lunduniversity.lu.se/lup/publication/2261125


2. I made use of ```curve_fit``` because it is easy to use, and readily provides the parameter (fit) error(s). I will investigate the many other options.

3. ```reproject_image_into_polar()```: Your solution ```theta = np.arctan2(x,y)``` looks like the best choice.

4. Not so much the time evaluate the polar coordinates, but that the operation would no doubt already have been done  in the speed calculation. Perhaps, we need one of @rth 's classes(?) to keep track of results. I will think about your other options.

5. The &theta; range allows for exclusion of the inverse Abel center image noise, and processing only one quadrant of an image that had been previously quadrant co-added.

 The ```r``` range specification is necessary to, provide for integration across a spectra feature (actually a simple ```.sum()```), to increase the signal/noise. This aspect is essential in order to extract a good estimate of the anisotropy parameter. Note, also, the &beta; depends on the kinetic energy of the electron, so each transition (peak) has a different anisotropy parameter. My code does not, yet, correctly, return multiple &beta; values.

(somehow stuffed up the item numbering)

**Comment by stggh** [comment]
To overcome @DanHickstein  issue 2) above I have split the anisotropy code into:
(a) ```calculate_anisotropy_distributions(IM, radial_ranges=None)``` and
(b) ```anisotropy_parameter(theta, intensity)```

```calculate_anisotropy_distributions()``` mirrors ```calculate_speeds()```, sums over the other axis

```anisotropy_parameter()``` performs the least-squares fit to <math>1+&beta;P<sub>2</sub>(cos&theta;)</math> to extract &beta;

Modified ```examples/example_anisotropy_parameter.py```
![example_anisotropy_parameter](https://cloud.githubusercontent.com/assets/10932229/12029056/2760a2be-ae36-11e5-97c9-799ca9ba7d15.png)

**Comment by DanHickstein** [comment]
Okay, this sounds good. I think that the BASEX.exe program returned the anisotropy parameter as a function of the radial coordinate (i.e., a whole array of beta values, one for each radial pixel). Is this something that is feasible here, or is the fitting too slow to make this practical? It's actually pretty slow in the BASEX.exe program as well (~5 seconds for 1000x1000 on a new i7 desktop if I recall).

**Comment by stggh** [comment]
In principle, this can be done. In practice, the fitting of &beta; may be nonsense, due to the low signal/noise of each `polarIM` column (theta), as indeed `basex.exe` returns for my photoelectron images.  For consistency with the old `basex.exe` formalism I will investigate whether it is sensible to provide this (mis-)feature.

**Comment by DanHickstein** [comment]
I just looked at the C-code for the anisotropy distributions in BASEX.exe (here is the relevant [function](https://gist.github.com/DanHickstein/a68e330bd5e290040cab), here is the whole [CalcThread.cpp](https://gist.github.com/DanHickstein/9ade3500dd29f88a85b3) file) and I'm not quite sure why it doesn't produce reliable results, since it's calculating the anisotropy distributions straight from the coefficients of the basis functions and not doing any fitting. I suppose that signal to noise could still play a role. Perhaps the centerline noise throws it off?

Anyway, we can, by default, use a coarser grid for generating the anisotropy versus r array in order to give us a better chance of having sufficient signal-to-noise. For example, we could use a bin size of, say, 3 radial pixels. It would make the calculation faster as well.

**Comment by stggh** [comment]
Perhaps, `basex.exe` is not calculating  `beta vs r`?

Through the magic of ssh, Linux, and Wine, I may run `basex.exe` on my Mac (at home, from an unix system at the ANU):
![o-basex-vmi](https://cloud.githubusercontent.com/assets/10932229/12135066/70b56760-b48a-11e5-8a12-78a6e5d1b08f.png)
The speed distribution is:
![o-basex-speed](https://cloud.githubusercontent.com/assets/10932229/12135091/c5f4899a-b48a-11e5-989d-a925571067ba.png)
The anisotropy distribution is:
![o-basex](https://cloud.githubusercontent.com/assets/10932229/12135087/b0dd89b2-b48a-11e5-968f-6c90be4e2929.png)
The above curve(s) make no sense to me.

PyAbel (hansenlaw) gives:
![o-anu1024](https://cloud.githubusercontent.com/assets/10932229/12135104/fde66c4c-b48a-11e5-9a26-6decb6390354.png)

radial-range   |   anisotropy parameter (β)
-----------------  |  ------------------------------------
    255-270     |   +0.10+-0.12
    275-295     |  -0.15+-0.04
    330-355     |  -0.18+-0.02

If we are talking about the same quantity, the PyAbel analysis provides 3 &beta; data points, for `r~262, 285, 340`.

The main peak fit is shown (right most plot). Note, for slow electrons (at 812 nm eKE is ~ 0.1 eV) the electron distribution is almost isotropic, &beta; has small values, and the fit, rightmost figure, looks poor.

PS: I realize that an image 1024x1024 pushes the 1000 limit of basex.exe, but 1024x  is what I had handy. I am pretty sure the same odd anisotropy data is still generated for sizes less than 1000.

**Comment by DanHickstein** [comment]
Hmmm, it's weird that the BASEX anisotropy looks so terrible. They published reasonable anisotropy values in Fig. 5 of their paper: http://www-bcf.usc.edu/~reisler/assets/pdf/67.pdf

As I recall, the BASEX.exe may be sensitive to the absolute values of your input image. What range of pixel intensities are you feeding into BASEX? Can you try multiplying them by 10, 1000, or maybe 0.01?

**Comment by stggh** [comment]
1) Changing the image size does little to improve the `...ansio.dat` data.

2) I have coded Eq. (16) of the BASEX paper (cited in the comment above)  <a href="https://gist.github.com/stggh/9021c22091d43741f063">here</a>

(my apologies for the poor plot structure)
![basex361](https://cloud.githubusercontent.com/assets/10932229/12165255/6d70f614-b570-11e5-954b-aba79a53c0de.png)

The image looks similar to Fig. 2. However, the inverse Abel transforms (`hansenlaw`, `basex`, and the original `basex.exe`) are substantially different to Fig.4 . I believe selected amplitudes may be different, i.e. not 2000, 200, 50. 

`abel.hansenlaw` and `abel.basex` agree with each other, but do not handle the inversion very well, possibly due to coarse a grid.  `basex.exe` is more like Fig. 4., but note that this may be due to the lack of negative values. 

The anisotropy from `basex.exe` is still crazy, it looks nothing like Fig. 5.

@DanHickstein the basex paper does not explain how &beta;  is extracted. The `.cpp` code has a `/baux1(0,0);` which may be causing an issue, but the radial data, similarly normalized(?) is fine. The is insufficient code to track down the method.

The ansiotropy parameters extracted from `tools.anisotropy_parameter()` give:
Calculating angular distribution:

radial-range   |   anisotropy parameter (β)
-----------------  | ------------------------------------
      5- 15        |    +1.24+-0.09
     10- 20       |    -1.44+-0.03
     15- 25       |     +0.45+-0.02
     65- 75       |     -0.14+-0.01
     80- 90       |    +2.37+-0.01
     95-105      |     -1.06+-0.01
    140-150     |     +4.81+-0.12
    150-160     |    +0.66+-0.00

The selected intensity variation for peak at radius 95-100 shown in 2nd right figure. Note, the intensity variation vs angle for the data(red) cf the fit (blue) differs for each 1/2, suggesting that the data center is not quite in the middle (another bug fix job to do).  Amazingly enough it has about the right value, <math>&beta;=-1<math>.

I think that further play with the basex model image `I(R, theta)`, is in order, scaling the amplitudes to give a speed distribution similar to Fig. 4, and perhaps, the `r`-grid to allow `hansenlaw` and `basex` to behave. I have noted in the past that the hansenlaw algorithm will overshoot due to too large a grid. I usually use a bigger image size, however a change of grid size `dr` may have the same effect.

Apologies, the above is very rushed ...

**Comment by DanHickstein** [comment]
Oh! I love that you have coded up the model image from the BASEX paper. Maybe you can add this function to ``abel.tools.py`` as something like ``sample_image_dribinski()``

Here is the complete c-code for BASEX in case you want to try to track down the problem with ``baux1``: https://dl.dropboxusercontent.com/u/3816350/BASEX%20C-code.zip
But, really, it's not our problem to fix BASEX.exe, we just need to make our own code work...

You are using an even image (316x316) right? I think that our BASEX method still works with odd-sized images.

**Comment by stggh** [comment]
>add this function to abel.tools.py as something like sample_image_dribinski()

Or elsewhere?  We have quite a few standard image functions (Gaussian -1D, -2D, 'curve A') in `abel.test_<method>.py` perhaps they can be combined into one file, and moved out of the directory `tests`? 
@rth has created `abel.analytical.py` with the comment:
>This file includes functions that have a known analytical Abel transform.
>They are used in unit testing as well for comparing different iAbel impementations.

but, IMO, the (nice python) `class` structure may discourage user examination of the functions. Perhaps, the non-class functions (including `abel_step_analytical()` and `sym_abel_step_1d()`) may be added at the top?

**Comment by stggh** [comment]
@DanHickstein, @rth, @DhrubajyotiDas 
As the result of testing some of the algorithms, I have found the origin of the  Fig. 4 (of the BASEX paper) vs calculated intensity difference in the speed profile (mentioned above). 

It is due to the lack of the Jacobian factor. If included the intensities agree with the published figure:
![test_dribinski](https://cloud.githubusercontent.com/assets/10932229/12390339/1eb3aa28-be33-11e5-97cf-82b887938fc3.png)
```python
# code to evaluate the speed profiles
from abel.hansenlaw import fabel_hansenlaw_transform, iabel_hansenlaw_transform#

#NB these imports have changed due to my implementation of how tools.py is split (open to change)
from abel.tools.analytical import sample_image_dribinski
from abel.tools.symmetry import get_image_quadrants
from abel.tools.vmi import calculate_speeds

import matplotlib.pyplot as plt

# BASEX sample image
IM = sample_image_dribinski(n=361)

# core transform(s) use top-right quadrant, Q0
Q0, Q1, Q2, Q3 = get_image_quadrants(IM)

# forward Abel transform
fQ0 = fabel_hansenlaw_transform(Q0)

# inverse Abel transform (of the forward Abel transform)
ifQ0 = iabel_hansenlaw_transform(fQ0)

# speed distributions, repeat for Jacobian=False
speed, radial_coords = calculate_speeds(ifQ0, origin=(0,0), Jacobian=True)

orig_speed, orig_radial = calculate_speeds(Q0, origin=(0,0), Jacobian=True)

#plot as required
```

**Comment by DanHickstein** [comment]
Awesome! That looks beautiful.

**Comment by DanHickstein** [comment]
It works!
