### ISSUE TITLE
Inverse Abel transform of quasi axis-symmetric images

### ISSUE THREAD

**Issue by rth** [PyAbel/PyAbel#62]
The real experimental data often has small deviations from the ideal up-down symmetry since,
  * the 3D object may present deviations from a perfect axis-symmetric case in the first place
  * manually deciding on what is the center of the image also indices some error bars. 

Indeed, if the up-down symmetry was ideal, we would only need half of the image to perform the inverse abel transform. There are  several usual ways of handling this issue,

1. Symmetrizing the original image (e.g. by taking the average of the left and right sides), then applying the transform on half the image. This is for instance done in `iabel_hansenlaw` and extended to the polar case with 4 quadrants. 

2. Applying a transform that will produce a axis-symmetrical reconstruction even for non axis-symmetric data (e.g. BASEX_asym).  I'm not sure whether this is in the end equivalent to method 1 or not.

3. Applying the inverse Abel transform  on the left and right sides separately then stitching the two results together (as mentioned in @DanHickstein's  [comment](https://github.com/PyAbel/PyAbel/issues/61#issuecomment-168464569))

4. Some as method 3. but enforcing the continuity on the axis (will be discussed later on).

To illustrate the limitations of the method 3, here is for instance the forward transform `F(y)` of a numerical function `f(r)`. We then choose a new symmetry axis with a small error (`r = -0.05`) to what it should be, and perform the inverse transform which yields `\tilde{f}`.

![quasi_symmetric_iabel](https://cloud.githubusercontent.com/assets/630936/12116672/db1c86a8-b3bb-11e5-9e51-f3d114df69b1.png)
The figure above is obtained with this [script](https://gist.github.com/rth/2310db2763fb62a072f3) using the last hansenlaw implementation from @stggh's fork for forward and inverse transform (BTW it works really well, better than the direct implementation for this example) .  The reconstruction is reasonable except on the origin when we have a discontinuity, which is typical when processing images with the method 3 (I don't know if @DhrubajyotiDas you had the same experience with this?). 

Method 1 (or 2)  does not have this limitation, however in a number of cases averaging the left and right sides could introduce artificial features, and applying the transform to the left and right sides separately would make more sense IMO. This is true for instance for the X-ray radiography image below (ignore the red line and the background) which is supposed to have a up-down symmetry although it is not perfect. 

![example](https://cloud.githubusercontent.com/assets/630936/12113627/2871f4fa-b3a4-11e5-90a0-7218285e396e.png)

The point of this issue is that for transforms that work on one half of the image ( hansenlaw, direct, three_point ) the way we render the image symmetric is
  * not unique (method 1, 3 or 4)
  * can be used for different implementations

So I would propose to move the code currently in [`_abel_hansenlaw_core`](https://github.com/stggh/PyAbel/blob/master/abel/hansenlaw.py#L255) under `symmetry.py` (or something similar) and see if we can make it work for different implementations. This also means that  the number of functions `hansenlaw.py` will be reduced to just 3 which are now called `fabel_hansenlaw_transform`,  `iabel_hansenlaw_transform`, `_abel_hansenlaw_transform_core`.

Regarding the `three_point` implementation (issue #61), this would mean that we won't need to handle any of this symmetrization stuff in `three_point.py`, but can merge it as it is now, after adding a few units tests. 

What do you think about this?  

BTW, if anybody has seen any approaches the literature to  apply the inverse Abel transform to the left and right sides separately, while regularizing the result on the axis in order to avoid a discontinuity, I would be most interested.

**Comment by DanHickstein** [comment]
@rth Great discussion! This is an important issue. I am writing a longer reply, but can you confirm that you are exclusively talking about left/right symmetry here? You write up/down symmetry at the beginning,  but I think that you are talking about left/right. (The axis of symmetry is in the vertical direction, so left/right symmetry is the type of symmetry that is required by the Abel transform. Up/down symmetry is not required, but often satisfied by photoelectron/photoion spectroscopy images.) The discussion of how we treat both symmetries is important, but the up/down is more straightforward.

**Comment by rth** [comment]
@DanHickstein Yes, you are right. I was talking about images with cylindrical symmetry (so left/right in our case, although the image above is rotated by 90° :) ). And indeed we would also need to  handle the polar symmetry (i.e. left/right *and* up/down case).

**Comment by DanHickstein** [comment]
Okay, maybe edit your post and rotate that image to avoid confusion? Then we can delete these comments.

**Comment by DanHickstein** [comment]
@rth Thanks for posting this! I have been thinking about this issue a lot in the past few weeks. We have some decisions to make regarding how we should handle image symmetry in general, and what is the responsibility of the individual transform functions. 

Recently, @DhrubajyotiDas revealed that it should be possible to make BASEX work on just one left/right half on an image (i.e., just a quarter of the original image, since he already cracked the up/down symmetry issue a while ago). This is exciting, because it opens the possibility that all of the basic transform functions can work on just one quarter of an image. 

I have a few thoughts:

1) The individual transform functions should do as little as is reasonable. Fundamentally, an Abel transform should be able to work on just a quarter of an image, and now it seems like all of the algorithms can do this. So, it makes sense for each transform method to just work on one side of an image (specifically the right side, to keep low r-values at low array index). We should move most of the symmetrization code into ``abel.tools.py``, and then we can allow the forthcoming ``abel.iabel/fabel`` function call the symmetrization functions or leave it to the user. This means that we need to implement the ``abel.fabel/iabel`` functions as soon as possible in order to ensure the same functionality. I'm not exactly sure what file these functions should live in. Something like ``abel/main.py``.

2) We should make a decision about what symmetrization options we want to provide, and then we can decide about exactly what functions are necessary to achieve this. I think that some users will want your Option 1 (average the left and right sides before the transform), which I'm pretty sure will be close enough to Option 2 (let the transform method itself do the averaging) that we can not worry about Option 2 (moreover, Option 2 so far only applies to the BASEX method). Many users will want Option 3 (transform left and right sides separately and stitch them together). Option 4 sounds like a nice option, but I don't know how to implement it.

@stggh started a discussion about how we could let the user select different symmetrization options: https://github.com/PyAbel/PyAbel/pull/49#issuecomment-162400477, but we did not deal with the case where the user does not want the entire image returned. It seems like if a user has selected to average all 4 quadrants, they might want the function to only return a single quadrant. For now, perhaps we can ignore this and always return the full image.

So, yes, we can merge three_point and let the ``iabel/fabel`` method worry about the symmetrization for all of the transform methods.

**Comment by DhrubajyotiDas** [comment]
@rth While I haven't personally explored what happens to the BASEX inversions when you intentionally drift from the proper center, I believe the authors stated that the further away you are from the center, the "lower" your resolution of the features in the inverted images. I'm not exactly sure what that means...

Regarding BASEX and real-world experimental data, my raw_data is frequently >= 500 pixels horizontally, and I can usually specify the center to within +/- 5 pixels with reasonable confidence. I haven't noticed any artifacts from moving the center of my images within this 10 pixel window, especially given how noisy the reconstructions are near the center.

**Comment by stggh** [comment]
@rth - thanks your comment on `_abel_hansenlaw_core()` working (for this case), and script.  Good to know.

Option 1  exploits symmetry to co-add quadrants, increasing the signal to noise. It relies on a 'perfect' symmetrical image (I have not coded, in python, the circularization method, yet).  If the image is not fully circular, in terms of spectral resolution, it may do more harm than good.

The same effect arises from having the image off-center.  The spectral feature 'walks' in `r` as a function of angle `theta`, increasing the integrated `r` width.  NB the intensity is conserved.

>further away you are from the center, the "lower" your resolution of the features in the inverted images.

The effect of a center offset by a fraction of a pixel (in 2048) are easily seen as an increase in FWHM in my O<sup>-</sup> photoelectron spectra. There is however a balance between determining the image center and the effects of image distortion.

In an ideal world returning a single quadrant, that contains all the experimental/transform information, is all that is needed. However, this generates complications for post analysis, unless the image is somehow tagged as a single quadrant. In principle, the user may call `tools.get_image_quadrants()` to extract a single, `Q0`, quadrant.

Option 2, post transform summation, is not equivalent to Option 1, because of the accumulated Abel transform noise. Both cases rely on good image symmetry, but this option does not hide the problem.
