### ISSUE TITLE
Rename hansenlaw?

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#63]
In the spirit of referring to all of the transform methods by a name that is descriptive of their algorithm (as was done in naming @DhrubajyotiDas's new algorithm ``three_point`` rather than ``dasch`` in https://github.com/PyAbel/PyAbel/issues/61), is it appropriate to rename @stggh's ``hansenlaw`` method to something more descriptive, like ``recursive``?

Just a thought, I don't feel that strongly about it and welcome thoughts from the rest of the team (@rth, @DhrubajyotiDas, @stggh).

**Comment by stggh** [comment]
I believe that the hansenlaw name should be kept. In this case, AFAIK, the authors derived the algorithm, and their paper deals with only the one method. Their, important work, has been lost to
the scientific community. It would be nice to maintain some historical acknowledgment.

I understand the argument to name the Abel transforms according to method. This works well for basex, and simplifies issues with multiple-author paper methods, but in general the program code is generated from a single source paper, and  in that case it is just as legitimate to name the method that reflects
the source author(s).   For @DhrubajyotiDas's  three_point algorithm, I actually prefer the name `dasch`.

If we decide to stick with method naming, then I think that `recursive` is too generic a term, and `state_variable` may be better.  The HL abstract states:
>The methods are based on a linear, space-variant, state-variable model of the Abel transform.

**Comment by DhrubajyotiDas** [comment]
I suppose one could make the case that the primary function of the names are to identify the different transform approaches unambiguously. If we take this to be the operative principle, 
* naming `hansenlaw` after its authors is consistent since (as @stggh mentioned) the authors derived the algorithm, and the cited paper only deals with this method, thus identifying it ambiguously
* naming the `dasch-three-point` method after its author is inconsistent because the author develops several different algorithms in the original paper, and it's necessary to specify which of these algorithms is implemented in PyAbel.

Regarding the `dasch-three-point` method, what about naming the `abel/<method>.py` to `abel/dasch.py`, with the functions inside being named `iabel_three_point_xxx()`? This way, if in the future we expand PyAbel to include the other algorithms in the Dasch paper, we could name them `iabel_two_point_xxx()` etc. inside `abel/dasch.py`. This also preserves the historical acknowledgement that Dasch deserves...

**Comment by rth** [comment]
+1 for keeping the `hansenlaw` and `three_point`  names. I do like putting the latter in `dasch.py`, although it slightly breaks the logic and I don't think that Dasch *et al.* were actually the first to use the 3pt and 2pt back-projection algorithms, as they say in the introduction,
> More recently, some practitioners^{2,3} have even suggested that the filtered back-projection techniques from two-dimensional tomography, numerically averaged over azimuthal angles, are better than either Abel or onion-peeling inversions.
this would allow to name them `iabel_3point` and `iabel_2point`, which is IMO nicer...

**Comment by DhrubajyotiDas** [comment]
@rth Just to be clear, the `three_point` method is not a filtered back-projection method. It's an analytical inverse-Abel integral involving a quadratic expansion of the line-of-sight data at every point.

**Comment by DanHickstein** [comment]
@DhrubajyotiDas, so you're saying that the Dasch paper was the first paper presenting the "three point" method?

Giving credit where credit is due should be one of our priorities, and we should decide how best to do this. Probably having a reference to the original manuscript in the docstring for each function should be a minimum. I agree with you that Hansen&Law seems like a forgotten gem. The speed of the transform and the quality seem excellent. 

I have no real problem using the author names, as long as the case is not ambiguous. I still think that the descriptive names might help reduce ambiguities, since it that often multiple papers are presenting identical methods. 

Is it better to have ``iabel_3point()`` and ``iabel_2point`` both in ``dash.py`` rather than in separate files? If they share a lot of code, I suppose this makes sense.

**Comment by DhrubajyotiDas** [comment]
@DanHickstein I'm not sure if Dasch was the first to think of the 3-point (or quadratic interpolation) technique, but I'm confident that his paper was the first to present it in the linear operator form. In my opinion *that* is the major utility of this method. Moreover, all subsequent references to the 3-point Abel technique that I've come across cite the Dasch 1992 paper as the reference. To the best of my knowledge, it would be acceptable to credit that paper for the `three_point` method in PyAbel. 

In the interests of consistency (separating each method into its own `.py` file), I'd be happy to have the files be named `abel/three_point.py`, especially since the documentation clearly credits Dasch for the technique.

**Comment by DanHickstein** [comment]
Okay, let's keep ``hansenlaw``. I'll close this issue. (Can always re-open if people want to discuss further, but I think that we have converged.)
