### ISSUE TITLE
Coordinating edits

### ISSUE THREAD

**Issue by DanHickstein** [PyAbel/PyAbel#79]
What are the @PyAbel/developers working on? 

When building the docs, I get a large amount of warnings because many of the docstrings are not quite in the perfect numpy docstring format. I would love to go through an fix all of these, at least to the extent that they do not throw warnings. 

But, I fear that this might cause a case of terrible overlapping edits if you are all working on various aspects of the code.

@DhrubajyotiDas, are you heading up the cleanup of `basex.py`? I think that @rth's effort to make the `abel.i/fabel` class is, to some extent, waiting for basex.py to be cleaned up.

**Comment by DhrubajyotiDas** [comment]
@DanHickstein Yes, I am cleaning up `basex.py`. By that I mean
- Setting defaults to values for parameters `center` and `n`
- Changing the name of the main `basex.py` function from `BASEX(...)` to `iabel_basex_transform(...)`

Unless there is something specific within these steps that is important for @rth's work to make the `abel/i/fabel` class, feel free to go ahead with that.

If I have my git straight, there shouldn't be any edit clashes if we merge PRs in the proper sequence.

**Comment by stggh** [comment]
@DanHickstein (welcome back!), excellent work on the doc generation.

I have recently changed `abel.tools.analytical.sample_image()`. The `class` part of this file has old style comments. The file structure requires an executive decision @PyAbel/developers as to whether `sample_image()` is implemented as a class method.  In addition, I believe that some of the `tests/` functions should be moved to `analytical.py` e.g. in  `test_hansenlaw.py`: `Curve A:  f(r), g(R)`. I think, somewhere, @DhrubajyotiDas also has the same function defined.

As for current activity I am:

1. checking on transform self-consistency, whole image vs quadrant, initially hansenlaw, and then the other methods. 
2. verifying that for even images `scipy.ndimage.shift(IM, (-1/2, 1/2))` followed by trimming one row/col `IM=IM[:-1, :-1]` is sufficient to provide an *identical* odd image. 
3. improvements to the example codes. I find `example_O2_PES_PAD.py` cloned from the original example templates to be too long winded and off-putting for a task that is simply: `IM=np.loadtxt("file"), AIM = iabel_<method>(IM), speed, radial = calculate_speeds(AIM)`.
For the simple GUI interface, `example_simple_GUI.py`, I would like to make it look more like the original `basex.exe`. I initially opted for buttons since Mac OXS pushed the menuitems to the toolbar, but I have changed my mind on this.
4. whether the image 2D test is necessary for `(f/i)abel_<method>()`.
5. longer term, code to circularize an image.

I think that documentation changes should easily merge, so there should be little to be concerned about.

**Comment by DhrubajyotiDas** [comment]
> I think, somewhere, @DhrubajyotiDas also has the same function defined.

@stggh, I've coded up that function and others [here](https://gist.github.com/DhrubajyotiDas/f8f531ca2cfa3fee6345).

**Comment by stggh** [comment]
Excellent! These functions should be adapted to live in `abel.tools.analytical.py` to be available for the unit tests.

**Comment by DanHickstein** [comment]
It sounds like most of these changes have been made. I will close this issue. Good work team!
