### ISSUE TITLE
class wrapper f/iabel hides parameter list

### ISSUE THREAD

**Issue by stggh** [PyAbel/PyAbel#93]
One problem with the `abel.iabel()`, `abel.fabel()` class wrappers is that they hide the parameter lists:
```python
In [1]: import abel

In [2]: abel.iabel?
Signature: abel.iabel(*args, **kwargs)
Docstring: <no docstring>
File:      ~/Software/Python/VMI/PyAbel/abel/transform.py
Type:      method

In [3]: abel.transform.AbelTransform?
Init signature: abel.transform.AbelTransform(self, IM, direction=None, method='three_point', center='none', verbose=True, vertical_symmetry=True, horizontal_symmetry=True, integrate=True, use_quadrants=(True, True, True, True), transform_options=(), center_options=())
This class provides a conveinent way to call all of transform functions
as well as the preprocessing (centering) and post processing 
(integration) functions. 
```

**Comment by rth** [comment]
Good point @stggh . We need to think about this a bit. Also, as to avoid lengthy discussions, that this subject seems to bring )) we could propose several prototypes for this wrapper class (essentially just an example of use) and vote on the solution that we prefer. The implementation is not so much of an issue, it's more about agreeing on what we want :).

**Comment by DanHickstein** [comment]
I have never actually used the question-mark notation in iPython! That's cool!

I think that if abel.iabel basically copied the docstring from `__init__`, then users should be able to figure it out. We can probably also copy the parameters in some facy way as well. 

But yes, I agree with @rth, we should settle on a format and move forward with it. At this point, I am open to most options, and am placing a little more emphasis on what will make the code easiest for people (like us!) to understand and maintain rather than what would be the fewest lines for the users.

This wrapper function doesn't necessarily need to be a class. The motivation for the class structure was that we might want to return several items from a transform, such as a speed distribution calculated from the basis set itself instead of from the image and we thought that the `results.transform` notation seemed cool. But at this point, none of the transform functions has the capability to do anything more than to provide the transformed image (well, Basex can provide the original image re-calculated from the basis set). And is there really a motivation for an object oriented structure here? Maybe we should just use functions.

Let's explore this option. For fun, I'm even going to do away with the fabel/iabel nomenclature as @stggh keeps suggesting. This would make the documentation easier and the code slightly shorter. The user would call something like this:
```python
import abel
centered_image = abel.tools.center.center_image(data, method='com')
transform = abel.transform(centered_image, direction='inverse', method='hansenlaw')
radial_intensity = abel.tools.vmi.angular_integration(transform)
```
note: here I am thinking that we should have a function "center_image()" which would be equivalent to calling "set_center( find_center(image) )".

I think that this method is simple, and will make a lot of sense to users that are familiar with the general scipy/numpy workflow, where each function accepts an array, modified it, and returns an array. It is also easy to implement.

Also, it would be easy for us to understand, since centering, calling the abel transform, and post-processing are all disconnected. And they are just simple functions. We will rely on our documentation and examples to communicate the workflow to the users.

It has one disadvantage: if we want to return anything other than the 2D transform, then the user will need to modify their code. For example, if we can calculate the radial_intensity distribution straight from the POP method (on the to-do list), then the user will need to modify their call:
```python
transform, radial_intensity = abel.transform(centered_image, direction='inverse', method='pop')
```

All said, this does not bother me that much. Alternatively, we could just have the transform function return a dictionary:
```python
results = abel.transform(centered_image, direction='inverse', method='pop')
transform = results['transform']
radial_intensity = results['radial_intensity']
```
or, it could be a one-liner:
```python
results = abel.transform(centered_image, direction='inverse', method='pop')['transform']
```

All said, I think that simple functions, with the transform function returning the dictionary, might be the fastest path for us to produce a reliable, working code.

**Comment by stggh** [comment]
@rth 
>to avoid lengthy discussions
Good point, many of my responses have been long winded.

@DanHickstein 
A dictionary is the go. This is what many scipy functions return. Any class structure  may be developed later.

At the moment PyAbel is broken and needs to be repaired asap.

**Comment by DanHickstein** [comment]
@stggh, we love your discussions, short or lengthy. :)

I should be able to put together the dict approach later today.

**Comment by DhrubajyotiDas** [comment]
@stggh always provides great insights. I welcome the discussions!

**Comment by stggh** [comment]
You guys are too kind. Short and sweet discussions will aid historical record.

**Comment by rth** [comment]
@stggh:  @DanHickstein and @DhrubajyotiDas   are right, my comment was not directed at all at you (nor anybody else for that matter),
 > we love your discussions, short or lengthy. :)
 > [..] and sweet discussions will aid historical record.

and that is certainly true :)

@PyAbel/developers  My point was more generally about how we make decisions in this project as (hopefully) more people join in. Essentially, right now, when we have to make some decision where opinions slightly  differ (which is normal), this leads to discussion that scales "badly" with the number of people involved. :)  And although I agree that we do need to discuss things, and I think we certainly all learn new things, the issue is that this also takes time, which could sometimes be better spent actually coding.  Therefore, I think that sometimes (in particular for topics where we have potential disagreements) , using more like a voting approach could be more efficient for making decisions (with 5 people there shouldn't be a draw). For instance, somebody proposes something, other says if they are for or against it, the proposal is accepted or rejected (in which case an updated version could be proposed later) and we more on.  Well that a proposition anyway.

On this note, I will go and write some code  for PyAbel  as it has been a while for me :)

**Comment by ldes89150** [comment]
Good discussion here!

My preference would be @DanHickstein 's first method
```python
import abel
centered_image = abel.tools.center.center_image(data, method='com')
transform = abel.transform(centered_image, direction='inverse', method='hansenlaw')
radial_intensity = abel.tools.vmi.angular_integration(transform)
```

However, it's also ok for me to use the dictionary.

**Comment by DhrubajyotiDas** [comment]
I like the dictionary approach because of the flexibility it provides us in providing output relevant to the parameters the user provides. Does the OOP approach provide any advantages that the dictionary approach cannot?

```python
centered_image = abel.tools.center.center_image(data, method='com')
```

IMO, `abel.tools.center.center_image` is extremely ugly, but I'm guessing this was just a quick example and not the final form of this sort of function call.

**Comment by DanHickstein** [comment]
Okay, so it seems like the dictionary solution is acceptable. Hurray! :)

@DhrubajyotiDas `abel.tools.center.center_image()` is where the function currently lives. I would also like a shorter function call, but not sure of the best solution. We can always change the names of things in the `abel/__init__.py`. For example, it might be a good idea to use 
`from .tools import *`
 so that we don't need to type `tools.` in any function calls. I'm not sure that it's too helpful for a user to know that something is a "tool".
Alternatively, I'm not sure if we actually need to "tools" subfolder...

**Comment by stggh** [comment]
Closed. 

Issue solved by a mammoth coding restructure by @DanHickstein. `abel.transform.py` has evolved from a class with a humongous instance function and sneaky (clever) class wrapping functions, to a function that returns a dictionary result. A much cleaner interface, with all function call parameters visible using the `ipython ?` query. Only fine-tuning required. The @PyAbel/developers and @ldes89150 are happy :-).
